(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const num=v=>{const x=Number(String(v??'').replace(/,/g,''));return Number.isFinite(x)?x:0};
const money=v=>'฿'+Math.round(num(v)).toLocaleString('th-TH');
const comma=v=>num(v)?num(v).toLocaleString('en-US',{maximumFractionDigits:2}):'';
function ensureQuickCalendar(){const q=$('#qDate');if(!q)return;const existing=$('.clean-date-row .clean-cal-btn');if(existing){existing.id='qCalendarBtn';$$('.clean-date-row .clean-cal-btn').slice(1).forEach(x=>x.remove());$$('#qNativeDate').slice(1).forEach(x=>x.remove());return}if($('#qCalendarBtn'))return;const holder=document.createElement('div');holder.className='clean-date-row';q.parentNode.insertBefore(holder,q);holder.appendChild(q);const b=document.createElement('button');b.type='button';b.id='qCalendarBtn';b.className='btn soft clean-cal-btn';b.textContent='📅 ปฏิทิน';holder.appendChild(b);let n=$('#qNativeDate');if(!n){n=document.createElement('input');n.type='date';n.id='qNativeDate';n.className='clean-native-date';holder.appendChild(n)}const toIso=v=>{const m=String(v||'').match(/^(\d{2})\/(\d{2})\/(\d{4})$/);return m?`${m[3]}-${m[2]}-${m[1]}`:''};const toTh=v=>{const m=String(v||'').match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?`${m[3]}/${m[2]}/${m[1]}`:''};b.onclick=()=>{n.value=toIso(q.value)||new Date().toISOString().slice(0,10);if(typeof n.showPicker==='function')n.showPicker();else n.click()};n.onchange=()=>{q.value=toTh(n.value);q.dispatchEvent(new Event('input',{bubbles:true}));q.dispatchEvent(new Event('change',{bubbles:true}))}}
function patchQuick(){ensureQuickCalendar();const save=$('#saveTxBtn');if(!save||save.dataset.parity)return;save.dataset.parity='1';const old=save.onclick;save.onclick=e=>{const amt=num($('#qAmt').value),m=$('#qDate').value.match(/^(\d{2})\/(\d{2})\/(\d{4})$/),date=m?`${m[3]}-${m[2]}-${m[1]}`:'',cat=$('#qCat').value,note=$('#qNote').value.trim(),type=$('#eBtn').classList.contains('danger')?'expense':'income';const dup=date&&amt&&(window.S?.tx||[]).some(x=>x.type===type&&x.date===date&&num(x.amount)===amt&&x.cat===cat&&String(x.note||'').trim()===note);if(dup&&!confirm(`พบรายการเหมือนกันแล้ว ${cat} ${money(amt)} วันที่ ${$('#qDate').value}\nต้องการบันทึกซ้ำจริงหรือไม่?`))return;if(old)old.call(save,e);setTimeout(()=>window.go?.('dash'),20)}}
const POS_KEY='spfm_ui_position_easy_v1';
const POS_A=[['💵','เงินสด / เงินฝาก','พร้อมใช้'],['📈','หุ้น / กองทุน / เงินลงทุน','ลงทุน'],['🪙','ทอง / สลาก / พันธบัตร','ลงทุน'],['🏠','บ้าน / คอนโด / ที่ดิน','ทรัพย์สิน'],['🚗','รถ','ทรัพย์สิน'],['📦','ทรัพย์สินอื่น','ทรัพย์สิน']];
const POS_D=[['🏠','หนี้บ้าน'],['🚗','หนี้รถ'],['💳','บัตรเครดิต / สินเชื่อ'],['📄','หนี้อื่น']];
function posState(){try{return JSON.parse(localStorage.getItem(POS_KEY)||'{}')}catch(e){return{}}}
function setPosState(k,v){const s=posState();s[k]=v;localStorage.setItem(POS_KEY,JSON.stringify(s))}
function ensurePositionCss(){if($('#cleanPosParityCss'))return;const s=document.createElement('style');s.id='cleanPosParityCss';s.textContent='.pos-fold-head{display:flex;align-items:center;gap:8px}.pos-fold-head h2{margin:0}.pos-fold-head .btn{margin-left:auto;white-space:nowrap}.pos-choice-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:9px;margin-top:12px}.pos-choice{border:1px solid #dfd4c5;background:#fff;border-radius:13px;padding:13px;text-align:left;font:inherit;font-weight:800;color:#342d25}.pos-choice span{font-size:22px;display:block;margin-bottom:5px}.pos-section{margin-top:12px;padding-top:10px;border-top:1px solid #e5ddd3}.pos-wizard{width:100%;margin:10px 0 12px}@media(max-width:520px){.pos-choice-grid{grid-template-columns:1fr 1fr}}';document.head.appendChild(s)}
function ensurePositionFolds(){ensurePositionCss();const st=posState();const setup=(bodyId,btnId,key,title)=>{const body=$('#'+bodyId),card=body?.closest('.card');if(!body||!card)return;let head=card.querySelector(':scope > .pos-fold-head');if(!head){const h=card.querySelector(':scope > h2');if(!h)return;head=document.createElement('div');head.className='pos-fold-head';card.insertBefore(head,h);head.appendChild(h)}const h=head.querySelector('h2');if(h)h.textContent=title;let btn=$('#'+btnId);if(!btn){btn=document.createElement('button');btn.type='button';btn.id=btnId;btn.className='btn soft';head.appendChild(btn)}let open=st[key]===true;const paint=()=>{body.hidden=!open;btn.textContent=open?'▲ ย่อ':'▼ เปิดดู'};btn.onclick=()=>{open=!open;setPosState(key,open);paint()};paint()};setup('assets','assetsFoldBtn','asset','รายละเอียดเงินและทรัพย์สิน');setup('debts','debtsFoldBtn','debt','รายละเอียดหนี้สิน')}
function posBindMoney(root){root?.querySelectorAll('input.money').forEach(el=>{el.addEventListener('input',()=>{const raw=el.value.replace(/,/g,'').replace(/[^0-9.]/g,'');if(!raw){el.value='';return}const p=raw.split('.');el.value=Number(p.shift()||0).toLocaleString('en-US')+(p.length?'.'+p.join('').slice(0,2):'')})})}
function posShow(){const m=$('#peModal');if(m)m.classList.add('on')}
function posClose(){const m=$('#peModal');if(m)m.classList.remove('on')}
function posChoice(type){const rows=type==='asset'?POS_A:POS_D;$('#peTitle').textContent=type==='asset'?'เพิ่มเงิน / ทรัพย์สิน':'เพิ่มหนี้';$('#peFields').innerHTML=`<div class="sub">เลือกประเภทก่อน ระบบจะถามเฉพาะข้อมูลที่จำเป็น</div><div class="pos-choice-grid">${rows.map((r,i)=>`<button type="button" class="pos-choice" data-pos-type="${type}" data-pos-i="${i}"><span>${r[0]}</span>${r[1]}</button>`).join('')}</div>`;const save=$('#peSave');save.style.display='none';$$('[data-pos-type]').forEach(b=>b.onclick=()=>posForm(b.dataset.posType,+b.dataset.posI));posShow()}
function posForm(type,i){const save=$('#peSave');save.style.display='block';save.textContent='บันทึก';if(type==='asset'){const r=POS_A[i];$('#peTitle').textContent=`${r[0]} ${r[1]}`;$('#peFields').innerHTML=`<label>ชื่อรายการ<input id="peName" placeholder="เช่น SCB ออมทรัพย์ / บ้าน / รถ"></label><label>มูลค่าปัจจุบันโดยประมาณ (บาท)<input id="peValue" class="money" inputmode="decimal" placeholder="0"></label>${i===3||i===4?`<div class="pos-section"><label><input id="peHasDebt" type="checkbox" style="width:auto"> รายการนี้ยังมีหนี้อยู่</label><div id="peDebtFields" style="display:none"><label>ยอดหนี้คงเหลือ<input id="peBalance" class="money" inputmode="decimal" placeholder="0"></label><label>ค่างวดต่อเดือน<input id="pePayment" class="money" inputmode="decimal" placeholder="0"></label></div></div>`:''}`;const has=$('#peHasDebt');if(has)has.onchange=()=>{$('#peDebtFields').style.display=has.checked?'block':'none'};posBindMoney($('#peFields'));save.onclick=()=>{const name=$('#peName').value.trim(),value=num($('#peValue').value);if(!name)return alert('กรุณาใส่ชื่อรายการ');S.assets.push({id:Date.now().toString(36),name,value,kind:r[2]});if(has?.checked){const bal=num($('#peBalance').value),pay=num($('#pePayment').value);if(bal>0)S.debts.push({id:(Date.now()+1).toString(36),name:'หนี้ '+name,balance:bal,payment:pay,rate:0})}posPersist()}}else{const r=POS_D[i];$('#peTitle').textContent=`${r[0]} ${r[1]}`;$('#peFields').innerHTML='<label>ชื่อหนี้<input id="peName" placeholder="เช่น บ้าน / รถ / บัตรเครดิต"></label><label>ยอดหนี้คงเหลือ<input id="peBalance" class="money" inputmode="decimal" placeholder="0"></label><label>ค่างวดต่อเดือน<input id="pePayment" class="money" inputmode="decimal" placeholder="0"></label>';posBindMoney($('#peFields'));save.onclick=()=>{const name=$('#peName').value.trim();if(!name)return alert('กรุณาใส่ชื่อหนี้');S.debts.push({id:Date.now().toString(36),name,balance:num($('#peBalance').value),payment:num($('#pePayment').value),rate:0});posPersist()}}posShow()}
function posPersist(){localStorage.setItem('spfm_public_v1',JSON.stringify(S));posClose();window.go?.('position');setTimeout(()=>{patchPosition();window.renderPositionParity?.()},0)}
function addPositionWizard(){const top=$('#pvCard');if(!top||$('#peWizardBtn'))return;const b=document.createElement('button');b.id='peWizardBtn';b.type='button';b.className='btn soft pos-wizard';b.textContent='✨ ช่วยฉันกรอกครั้งแรก';b.onclick=()=>{posChoice('asset')};top.insertAdjacentElement('afterend',b)}
function wirePositionActions(){const a=$('#addAssetBtn'),d=$('#addDebtBtn');if(a)a.onclick=()=>posChoice('asset');if(d)d.onclick=()=>posChoice('debt')}
function patchPosition(){const assets=$('#assets'),debts=$('#debts');if(!assets||!debts)return;ensurePositionFolds();window.renderPositionParity=function(){if(!window.S)return;assets.innerHTML=S.assets.length?S.assets.map((x,i)=>`<div class="item"><input value="${String(x.name||'').replace(/"/g,'&quot;')}" data-a-name="${i}"><div class="grid g2"><input class="money" value="${comma(x.value)}" data-a-value="${i}"><select data-a-kind="${i}"><option ${x.kind==='พร้อมใช้'?'selected':''}>พร้อมใช้</option><option ${x.kind==='ลงทุน'?'selected':''}>ลงทุน</option><option ${x.kind==='Emergency'?'selected':''}>Emergency</option><option ${x.kind==='เกษียณ'?'selected':''}>เกษียณ</option><option ${x.kind==='ทรัพย์สิน'?'selected':''}>ทรัพย์สิน</option><option ${x.kind==='ทรัพย์สินอื่น'?'selected':''}>ทรัพย์สินอื่น</option></select></div><button class="btn danger" data-a-del="${i}">ลบ</button></div>`).join(''):'<div class="sub">ยังไม่มีทรัพย์สิน</div>';debts.innerHTML=S.debts.length?S.debts.map((x,i)=>`<div class="item"><input value="${String(x.name||'').replace(/"/g,'&quot;')}" data-d-name="${i}"><div class="grid g2"><label>ยอดคงเหลือ<input class="money" value="${comma(x.balance)}" data-d-bal="${i}"></label><label>ค่างวด/เดือน<input class="money" value="${comma(x.payment)}" data-d-pay="${i}"></label></div><label>ดอกเบี้ยต่อปี (%)<input type="number" step="0.01" value="${num(x.rate)}" data-d-rate="${i}"></label><button class="btn danger" data-d-del="${i}">ลบ</button></div>`).join(''):'<div class="sub">ยังไม่มีหนี้</div>';$$('[data-a-name]').forEach(e=>e.onchange=()=>{S.assets[+e.dataset.aName].name=e.value;saveAndRender()});$$('[data-a-value]').forEach(e=>e.onchange=()=>{S.assets[+e.dataset.aValue].value=num(e.value);saveAndRender()});$$('[data-a-kind]').forEach(e=>e.onchange=()=>{S.assets[+e.dataset.aKind].kind=e.value;saveAndRender()});$$('[data-a-del]').forEach(e=>e.onclick=()=>{S.assets.splice(+e.dataset.aDel,1);saveAndRender()});$$('[data-d-name]').forEach(e=>e.onchange=()=>{S.debts[+e.dataset.dName].name=e.value;saveAndRender()});$$('[data-d-bal]').forEach(e=>e.onchange=()=>{S.debts[+e.dataset.dBal].balance=num(e.value);saveAndRender()});$$('[data-d-pay]').forEach(e=>e.onchange=()=>{S.debts[+e.dataset.dPay].payment=num(e.value);saveAndRender()});$$('[data-d-rate]').forEach(e=>e.onchange=()=>{S.debts[+e.dataset.dRate].rate=num(e.value);saveAndRender()});$$('[data-d-del]').forEach(e=>e.onclick=()=>{S.debts.splice(+e.dataset.dDel,1);saveAndRender()});ensurePositionFolds();wirePositionActions();addPositionWizard()};function saveAndRender(){localStorage.setItem('spfm_public_v1',JSON.stringify(S));window.renderPositionParity()};setTimeout(()=>{window.renderPositionParity();wirePositionActions();addPositionWizard()},0)}
function patchSettings(){const s=$('#settings');if(!s)return;const income=$('#sIncome')?.closest('label');if(income){const n=[...income.childNodes].find(x=>x.nodeType===3&&x.nodeValue.trim());if(n)n.nodeValue='เงินสำหรับใช้จ่าย/เดือน (หลังแยกเงินออมแล้ว)'}const saveBtn=$('#saveSettingsBtn');if(saveBtn)saveBtn.textContent='บันทึกการตั้งค่า';const back=$('#backupBtn');if(back&&!back.dataset.parity){back.dataset.parity='1';const old=back.onclick;back.onclick=e=>{old?.call(back,e);setTimeout(()=>alert('สำรองข้อมูลแล้ว กรุณาเก็บไฟล์นี้ไว้ เผื่อเปลี่ยนเครื่องหรือต้องกู้คืนข้อมูล'),50)}}const restore=$('#restore');if(restore&&!restore.dataset.parity){restore.dataset.parity='1';const old=restore.onchange;restore.onchange=e=>{if(!e.target.files?.[0])return;if(!confirm('กู้คืนข้อมูลจากไฟล์นี้? ข้อมูลปัจจุบันในแอปจะถูกแทนที่ด้วยข้อมูลจากไฟล์สำรอง')){e.target.value='';return}old?.call(restore,e)}}}
function patchFirstStart(){const m=$('#mpfFirstStart');if(!m||m.dataset.parity)return;m.dataset.parity='1';const h=m.querySelector('h2'),sub=m.querySelector('.sub'),btn=$('#firstStartSettingsBtn');if(h)h.textContent='เริ่มต้นที่ “ตั้งค่า”';if(sub)sub.textContent='ก่อนใช้งาน ให้กำหนดเงินสำหรับใช้จ่าย/เดือน เงินออม ค่าใช้จ่ายประจำ และค่าใช้จ่ายรายปี ระบบจะคำนวณเงินที่ควรใช้จริงให้';if(btn)btn.textContent='ไปที่ตั้งค่า';if(!m.querySelector('.later')){const b=document.createElement('button');b.type='button';b.className='btn soft save-wide later';b.textContent='ไว้ก่อน';b.onclick=()=>{localStorage.setItem('mpf_first_start_notice_v1','1');m.classList.remove('on')};btn?.insertAdjacentElement('afterend',b)}}
function preserveUnknownData(){try{const raw=JSON.parse(localStorage.getItem('spfm_public_v1')||'{}');if(!raw||typeof raw!=='object'||!window.S)return;for(const [k,v] of Object.entries(raw))if(!(k in S))S[k]=v}catch{}}
function init(){preserveUnknownData();patchQuick();patchPosition();patchSettings();patchFirstStart();$$('.tabs button').forEach(b=>b.addEventListener('click',()=>setTimeout(()=>{patchQuick();patchPosition();patchSettings();patchFirstStart()},0)));$('#settingsBtn')?.addEventListener('click',()=>setTimeout(patchSettings,0))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,0));else setTimeout(init,0);
})();