(()=>{
'use strict';
const KEY='spfm_public_v1',FIRST='mpf_first_start_notice_v1';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const n=v=>{const x=Number(String(v??'').replace(/,/g,''));return Number.isFinite(x)?x:0};
const money=v=>'฿'+Math.round(n(v)).toLocaleString('th-TH');
const comma=v=>n(v)?n(v).toLocaleString('en-US',{maximumFractionDigits:2}):'';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const id=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const todayISO=()=>{const d=new Date();return d.toISOString().slice(0,10)};
const isoToThai=d=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(String(d)))return d||'';const [y,m,day]=d.split('-');return `${day}/${m}/${y}`};
const thaiToIso=s=>{const m=String(s||'').match(/^(\d{2})\/(\d{2})\/(\d{4})$/);if(!m)return '';const [,d,mo,y]=m;const dt=new Date(`${y}-${mo}-${d}T00:00:00`);return Number.isNaN(dt.getTime())?'':`${y}-${mo}-${d}`};
const monthKey=iso=>String(iso||'').slice(0,7);
function blank(){return{profile:{name:'',income:0,saving:0,emerTarget:6,initialized:false},plans:[],annual:[],assets:[],debts:[],goals:[],tx:[]}}
function normalize(x){const b=blank(),o=(x&&typeof x==='object')?x:{};return{profile:{...b.profile,...(o.profile||{})},plans:Array.isArray(o.plans)?o.plans:[],annual:Array.isArray(o.annual)?o.annual:[],assets:Array.isArray(o.assets)?o.assets:[],debts:Array.isArray(o.debts)?o.debts:[],goals:Array.isArray(o.goals)?o.goals:[],tx:Array.isArray(o.tx)?o.tx:[]}}
let S=(()=>{try{return normalize(JSON.parse(localStorage.getItem(KEY)||'null'))}catch(e){return blank()}})();window.S=S;
function save(){localStorage.setItem(KEY,JSON.stringify(S));window.S=S}
function plan(){const inc=n(S.profile.income),ex=S.plans.reduce((a,x)=>a+n(x.amount),0),an=S.annual.reduce((a,x)=>a+n(x.amount),0)/12;return{inc,ex,an,remain:inc-ex-an}}
window.plan=plan;
function ac(){let liquid=0,invest=0,total=0,emer=0;for(const a of S.assets){const v=n(a.value);total+=v;const k=String(a.kind||'').toLowerCase();if(/พร้อม|เงินสด|ฝาก|liquid/.test(k))liquid+=v;else invest+=v;if(/emergency|ฉุกเฉิน/.test(k))emer+=v}const debt=S.debts.reduce((a,x)=>a+n(x.balance),0);return{liquid,invest,total,debt,net:total-debt,emer}}
window.ac=ac;
function debtPayment(){return S.debts.reduce((a,x)=>a+n(x.payment),0)}
function currentMonthTx(){const m=todayISO().slice(0,7);return S.tx.filter(x=>monthKey(x.date)===m)}
function visible(el,on){if(typeof el==='string')el=$(el);if(el)el.classList.toggle('on',!!on)}
function setText(sel,v){const e=$(sel);if(e)e.textContent=v}
function setWidth(sel,p){const e=$(sel);if(e)e.style.width=Math.max(0,Math.min(100,p))+'%'}
function formatMoneyInput(el){if(!el)return;const raw=String(el.value||'').replace(/,/g,'').replace(/[^0-9.]/g,'');if(!raw){el.value='';return}const parts=raw.split('.');const whole=parts.shift()||'0',dec=parts.join('').slice(0,2);el.value=Number(whole).toLocaleString('en-US')+(dec?'.'+dec:'')}
function bindMoney(root=document){root.querySelectorAll('input.money').forEach(el=>{if(el.dataset.moneyBound)return;el.dataset.moneyBound='1';el.addEventListener('input',()=>formatMoneyInput(el))})}
function toast(msg='✓ บันทึกสำเร็จ'){document.querySelector('.toast')?.remove();const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),1600)}
function go(page){$$('.page').forEach(x=>x.classList.toggle('on',x.id===page));$$('.tabs button').forEach(x=>x.classList.toggle('on',x.dataset.p===page));localStorage.setItem('mpf_last_page_v1',page);if(page==='hist')renderHistory();if(page==='future')renderFuture();if(page==='position')renderPosition();window.scrollTo({top:0,behavior:'instant'})}
window.go=go;
function renderDashboard(){const p=plan(),a=ac(),tx=currentMonthTx(),monthExp=tx.filter(x=>x.type==='expense').reduce((q,x)=>q+n(x.amount),0);setText('#dRemain',money(p.remain));setText('#dMonth',money(monthExp));setText('#dNet',money(a.net));const remainRate=p.inc?Math.max(-999,p.remain/p.inc*100):0;const saveRate=p.inc?n(S.profile.saving)/p.inc*100:0;const debtRate=p.inc?debtPayment()/p.inc*100:0;setText('#healthRemain',remainRate.toFixed(1)+'%');setText('#healthSave',saveRate.toFixed(1)+'%');setText('#healthDebt',debtRate.toFixed(1)+'%');setText('#healthRemainText',remainRate>=20?'อยู่ในแผน':remainRate>=10?'พอใช้':'ควรทบทวน');setText('#healthSaveText',saveRate>=20?'ดี':saveRate>=10?'พอใช้':'ควรเพิ่ม');setText('#healthDebtText',debtRate<=30?'อยู่ในเกณฑ์':debtRate<=40?'เริ่มสูง':'สูง');const needed=Math.max(1,p.ex+p.an),emerMonths=a.emer/needed,target=Math.max(1,n(S.profile.emerTarget)||6);setText('#aEmer',emerMonths.toFixed(1)+' เดือน');setText('#emerValue',money(a.emer));setWidth('#emerProgress',emerMonths/target*100);setText('#healthAdvice',emerMonths<target?`เงินสำรองฉุกเฉินยังต่ำกว่าเป้าหมาย ${target} เดือน`:'เงินสำรองฉุกเฉินถึงเป้าหมายแล้ว');renderDashGoals()}
function goalMarkup(g,actions=false){const t=n(g.target),c=n(g.current),pc=t?Math.min(100,Math.max(0,c/t*100)):0;return `<div class="item"><div class="section-head"><div><b>${esc(g.name||'เป้าหมาย')}</b><div class="sub">${money(c)} / ${money(t)}</div></div><div><b>${Math.round(pc)}%</b>${actions?`<div class="item-actions" style="margin-top:5px"><button class="btn soft" data-goal-edit="${esc(g.id)}">แก้ไข</button><button class="btn danger" data-goal-del="${esc(g.id)}">ลบ</button></div>`:''}</div></div><div class="progress"><i style="width:${pc}%"></i></div></div>`}
function renderDashGoals(){const root=$('#dashGoals');if(!root)return;const gs=S.goals.filter(g=>n(g.target)>0);root.innerHTML=gs.length?gs.slice(0,3).map(g=>goalMarkup(g)).join('')+(gs.length>3?`<div class="sub" style="margin-top:8px">และอีก ${gs.length-3} เป้าหมาย</div>`:''):'<div class="sub">ยังไม่มีเป้าหมายการเงิน</div>'}
const expenseCats=['อาหาร','ที่อยู่อาศัย','ครอบครัว','การเดินทาง','สุขภาพ','ช้อปปิ้ง','สื่อสาร','การศึกษา','ท่องเที่ยว','อื่น ๆ'];const incomeCats=['เงินเดือน','รายได้เสริม','โบนัส','คืนเงิน','ขายของ','อื่น ๆ'];let qtype='expense';
function paintType(){const e=$('#eBtn'),i=$('#iBtn');e.className='btn '+(qtype==='expense'?'danger':'soft');i.className='btn '+(qtype==='income'?'gold':'soft');renderCats()}
function catIcon(cat){if(/อาหาร/.test(cat))return '🍽';if(/ที่อยู่/.test(cat))return '⌂';if(/ครอบ/.test(cat))return '♧';if(/เดินทาง/.test(cat))return '🚗';if(/สุขภาพ/.test(cat))return '♡';if(/ช้อป/.test(cat))return '▣';if(/สื่อสาร/.test(cat))return '▯';if(/ศึกษา/.test(cat))return '▤';if(/ท่อง/.test(cat))return '✈';if(/เงินเดือน/.test(cat))return '฿';if(/รายได้/.test(cat))return '+';return '○'}
function renderCats(){const cats=qtype==='expense'?expenseCats:incomeCats,sel=$('#qCat'),strip=$('#qCatStrip');const old=sel.value;sel.innerHTML=cats.map(c=>`<option>${c}</option>`).join('');if(cats.includes(old))sel.value=old;strip.innerHTML=cats.map(c=>`<button type="button" class="cat-chip ${sel.value===c?'on':''}" data-cat="${esc(c)}"><span class="ico">${catIcon(c)}</span>${esc(c)}</button>`).join('');strip.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{sel.value=b.dataset.cat;renderCats();dupCheck()})}
function dateTyping(el){let d=String(el.value||'').replace(/\D/g,'').slice(0,8);if(d.length>4)d=d.slice(0,2)+'/'+d.slice(2,4)+'/'+d.slice(4);else if(d.length>2)d=d.slice(0,2)+'/'+d.slice(2);el.value=d}
function dupCheck(){const iso=thaiToIso($('#qDate').value),amt=n($('#qAmt').value),cat=$('#qCat').value,note=$('#qNote').value.trim();const found=iso&&amt&&S.tx.some(x=>x.date===iso&&n(x.amount)===amt&&x.cat===cat&&String(x.note||'').trim()===note);const d=$('#dup');d.style.display=found?'block':'none';d.textContent=found?'พบรายการที่อาจซ้ำกับข้อมูลเดิม โปรดตรวจสอบก่อนบันทึก':''}
function saveTx(){const amt=n($('#qAmt').value),date=thaiToIso($('#qDate').value),cat=$('#qCat').value,note=$('#qNote').value.trim();if(amt<=0){alert('กรุณาใส่จำนวนเงินมากกว่า 0');return}if(!date){alert('กรุณาใส่วันที่รูปแบบ dd/mm/yyyy');return}S.tx.unshift({id:id(),type:qtype,amount:amt,cat,date,note});save();$('#qAmt').value='';$('#qNote').value='';dupCheck();renderAll();toast()}
function renderRecent(){const root=$('#recent');if(!root)return;const m=todayISO().slice(0,7),rows=S.tx.filter(x=>monthKey(x.date)===m).slice(0,8);root.innerHTML=rows.length?rows.map(txRow).join(''):'<div class="sub">ยังไม่มีรายการเดือนนี้</div>'}
function txRow(x){return `<div class="row"><span><b>${esc(x.cat||'-')}</b><div class="sub">${isoToThai(x.date)}${x.note?' • '+esc(x.note):''}</div></span><b class="${x.type==='expense'?'status-bad':'status-good'}">${x.type==='expense'?'-':'+'}${money(x.amount)}</b></div>`}
let histMode='list',calDate=new Date();
function filteredHistory(){const mon=$('#hMonth').value,type=$('#hType').value,q=$('#hSearch').value.trim().toLowerCase();return S.tx.filter(x=>(!mon||monthKey(x.date)===mon)&&(type==='all'||x.type===type)&&(!q||`${x.cat} ${x.note||''}`.toLowerCase().includes(q)))}
function renderHistory(){const rows=filteredHistory(),inc=rows.filter(x=>x.type==='income').reduce((a,x)=>a+n(x.amount),0),exp=rows.filter(x=>x.type==='expense').reduce((a,x)=>a+n(x.amount),0);setText('#hInc',money(inc));setText('#hExp',money(exp));$('#history').innerHTML=rows.length?rows.map(txRow).join(''):'<div class="sub" style="padding:12px 0">ไม่พบรายการ</div>';renderCalendar();renderAnalysis()}
function renderCalendar(){const title=$('#hcTitle'),grid=$('#calendarGrid');if(!title||!grid)return;const y=calDate.getFullYear(),m=calDate.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate();title.textContent=calDate.toLocaleDateString('th-TH',{month:'long',year:'numeric'});let html='';for(let i=0;i<first.getDay();i++)html+='<div></div>';for(let d=1;d<=days;d++){const iso=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,sum=S.tx.filter(x=>x.date===iso&&x.type==='expense').reduce((a,x)=>a+n(x.amount),0);html+=`<div class="cal-day"><b>${d}</b>${sum?`<div class="status-bad">${Math.round(sum).toLocaleString()}</div>`:''}</div>`}grid.innerHTML=html}
function renderAnalysis(){const mon=$('#hMonth').value||todayISO().slice(0,7),rows=S.tx.filter(x=>x.type==='expense'&&monthKey(x.date)===mon),map={};rows.forEach(x=>map[x.cat||'อื่น ๆ']=(map[x.cat||'อื่น ๆ']||0)+n(x.amount));const entries=Object.entries(map).sort((a,b)=>b[1]-a[1]),total=entries.reduce((a,x)=>a+x[1],0);const colors=['#b58a45','#79654a','#b9a488','#8c765b','#d0b98f','#6d5d4b','#c99764','#9c8b79'];let deg=0,parts=[];entries.forEach(([k,v],i)=>{const a=total?v/total*360:0;parts.push(`${colors[i%colors.length]} ${deg}deg ${deg+a}deg`);deg+=a});$('#histDonut').style.background=parts.length?`conic-gradient(${parts.join(',')})`:'#ede6dc';$('#histLegend').innerHTML=entries.length?entries.slice(0,6).map(([k,v],i)=>`<div><span style="display:inline-block;width:9px;height:9px;border-radius:50%;background:${colors[i%colors.length]};margin-right:5px"></span>${esc(k)} ${total?Math.round(v/total*100):0}%</div>`).join(''):'ยังไม่มีรายจ่ายเดือนนี้';const max=entries[0]?.[1]||1;$('#histBars').innerHTML=entries.map(([k,v])=>`<div class="bar-row"><span>${esc(k)}</span><div class="bar-track"><div class="bar-fill" style="width:${v/max*100}%"></div></div><b>${money(v)}</b></div>`).join('')}
function showHistMode(mode){histMode=mode;$$('#histCalTabs button').forEach(b=>b.classList.toggle('on',b.dataset.hist===mode));$('#histListWrap').style.display=mode==='list'?'block':'none';$('#histCalCard').style.display=mode==='calendar'?'block':'none';$('#histAnalysisWrap').style.display=mode==='analysis'?'block':'none';renderHistory()}
function renderPosition(){const a=ac();setText('#pvAssetsTotal',money(a.total));setText('#pvDebtTotal',money(a.debt));setText('#pvNet',money(a.net));setText('#pvLiquidText',money(a.liquid));setText('#pvInvestText',money(a.invest));setText('#pvDebtText',money(a.debt));const max=Math.max(1,a.liquid,a.invest,a.debt);setWidth('#pvLiquidBar',a.liquid/max*100);setWidth('#pvInvestBar',a.invest/max*100);setWidth('#pvDebtBar',a.debt/max*100);$('#assets').innerHTML=S.assets.length?S.assets.map(x=>`<div class="item"><div class="section-head"><span><b>${esc(x.name||'ทรัพย์สิน')}</b><div class="sub">${esc(x.kind||'')}</div></span><b>${money(x.value)}</b></div></div>`).join(''):'<div class="sub">ยังไม่มีทรัพย์สิน</div>';$('#debts').innerHTML=S.debts.length?S.debts.map(x=>`<div class="item"><div class="section-head"><span><b>${esc(x.name||'หนี้')}</b><div class="sub">ผ่อน ${money(x.payment)}/เดือน • ${n(x.rate).toLocaleString()}%</div></span><b>${money(x.balance)}</b></div></div>`).join(''):'<div class="sub">ยังไม่มีหนี้</div>'}
let peType='asset';function openPE(type){peType=type;setText('#peTitle',type==='asset'?'เพิ่มเงิน / ทรัพย์สิน':'เพิ่มหนี้');setText('#peSub',type==='asset'?'บันทึกมูลค่าปัจจุบัน':'บันทึกยอดคงเหลือและภาระผ่อน');$('#peFields').innerHTML=type==='asset'?`<label>ชื่อ<input id="peName" placeholder="เช่น เงินฝาก / กองทุน"></label><label>ประเภท<select id="peKind"><option>พร้อมใช้</option><option>ลงทุน</option><option>Emergency</option><option>ทรัพย์สินอื่น</option></select></label><label>มูลค่า<input id="peValue" class="money" inputmode="decimal"></label><button id="peSave" class="btn dark save-wide" type="button">บันทึก</button>`:`<label>ชื่อหนี้<input id="peName" placeholder="เช่น บ้าน / รถ / บัตรเครดิต"></label><label>ยอดคงเหลือ<input id="peBalance" class="money" inputmode="decimal"></label><label>ผ่อนต่อเดือน<input id="pePayment" class="money" inputmode="decimal"></label><label>ดอกเบี้ยต่อปี (%)<input id="peRate" type="number" step="0.01"></label><button id="peSave" class="btn dark save-wide" type="button">บันทึก</button>`;bindMoney($('#peFields'));$('#peSave').onclick=savePE;visible('#peModal',true)}
function savePE(){const name=$('#peName').value.trim();if(!name){alert('กรุณาใส่ชื่อ');return}if(peType==='asset'){const value=n($('#peValue').value);if(value<0){alert('มูลค่าต้องไม่ติดลบ');return}S.assets.push({id:id(),name,kind:$('#peKind').value,value})}else{const balance=n($('#peBalance').value),payment=n($('#pePayment').value),rate=n($('#peRate').value);S.debts.push({id:id(),name,balance,payment,rate})}save();visible('#peModal',false);renderAll();toast()}
let editingGoal=null;function openGoal(g=null){editingGoal=g?.id||null;setText('#goalModalTitle',g?'แก้ไขเป้าหมายการเงิน':'เพิ่มเป้าหมายการเงิน');$('#mpfGoalName').value=g?.name||'';$('#mpfGoalTarget').value=g?comma(g.target):'';$('#mpfGoalCurrent').value=g?comma(g.current):'';$('#mpfGoalError').style.display='none';visible('#mpfGoalModal',true)}
function saveGoal(){const name=$('#mpfGoalName').value.trim(),target=n($('#mpfGoalTarget').value),current=Math.max(0,n($('#mpfGoalCurrent').value));const er=$('#mpfGoalError');if(!name||target<=0){er.style.display='block';er.textContent=!name?'กรุณาใส่ชื่อเป้าหมาย':'กรุณาใส่ยอดเป้าหมายมากกว่า 0';return}if(editingGoal){const g=S.goals.find(x=>String(x.id)===String(editingGoal));if(g)Object.assign(g,{name,target,current})}else S.goals.push({id:id(),name,target,current});save();visible('#mpfGoalModal',false);editingGoal=null;renderAll();toast()}
function renderFuture(){const root=$('#goalList');root.innerHTML=S.goals.length?S.goals.map(g=>goalMarkup(g,true)).join(''):'<div class="sub">ยังไม่มีเป้าหมายการเงิน</div>';root.querySelectorAll('[data-goal-edit]').forEach(b=>b.onclick=()=>openGoal(S.goals.find(g=>String(g.id)===b.dataset.goalEdit)));root.querySelectorAll('[data-goal-del]').forEach(b=>b.onclick=()=>{if(confirm('ลบเป้าหมายนี้?')){S.goals=S.goals.filter(g=>String(g.id)!==b.dataset.goalDel);save();renderAll()}});const sel=$('#wfGoal'),cur=sel.value;sel.innerHTML='<option value="">— เลือกเป้าหมาย —</option>'+S.goals.filter(g=>n(g.target)>0).map(g=>`<option value="${esc(g.id)}">${esc(g.name)} • ${money(g.current)} / ${money(g.target)}</option>`).join('');if([...sel.options].some(o=>o.value===cur))sel.value=cur;futureCalc()}
function guessType(name){const s=String(name||'').toLowerCase();if(/รถ|car/.test(s))return'car';if(/บ้าน|home|house/.test(s))return'home';return'other'}
function useGoal(idv){const g=S.goals.find(x=>String(x.id)===String(idv));if(!g)return;$('#wfType').value=guessType(g.name);$('#wfPrice').value=comma(g.target);$('#wfCash').value=comma(g.current);$('#wfLoan').value='';futureCalc()}
function futureCalc(){const price=n($('#wfPrice').value),cash=n($('#wfCash').value),loan=n($('#wfLoan').value)||(Math.max(0,price-cash)),years=Math.max(1,n($('#wfYears').value)||5),rate=Math.max(0,n($('#wfRate').value)),months=years*12,r=rate/100/12;let payment=0;if(loan>0)payment=r?loan*r*Math.pow(1+r,months)/(Math.pow(1+r,months)-1):loan/months;const inc=n(S.profile.income),currentDebt=debtPayment(),newRate=inc?(currentDebt+payment)/inc*100:0;$('#wfResult').innerHTML=price||loan?`ยอดที่ต้องใช้ <b>${money(price)}</b><br>ยอดกู้โดยประมาณ <b>${money(loan)}</b><br>ค่างวดเพิ่มโดยประมาณ <b>${money(payment)}/เดือน</b><br>ภาระผ่อนรวมหลังจำลอง <b>${newRate.toFixed(1)}%</b>`:'กรอกข้อมูลเพื่อดูผลจำลอง'}
function settings(open){if(open){$('#sName').value=S.profile.name||'';$('#sIncome').value=comma(S.profile.income);$('#sSaving').value=comma(S.profile.saving);$('#sEmerTarget').value=n(S.profile.emerTarget)||6;renderSettingsLists();window.setTimeout(()=>$('#settings .sheet').scrollTop=0,0)}visible('#settings',open)}window.settings=settings;
function renderSettingsLists(){const make=(x,type)=>`<div class="item"><div class="section-head"><span><b>${esc(x.name||'-')}</b></span><div><b>${money(x.amount)}</b> <button class="btn danger" data-del-${type}="${esc(x.id)}" type="button">ลบ</button></div></div></div>`;$('#planList').innerHTML=S.plans.length?S.plans.map(x=>make(x,'plan')).join(''):'<div class="sub">ยังไม่มีรายการ</div>';$('#annualList').innerHTML=S.annual.length?S.annual.map(x=>make(x,'annual')).join(''):'<div class="sub">ยังไม่มีรายการ</div>';$$('[data-del-plan]').forEach(b=>b.onclick=()=>{S.plans=S.plans.filter(x=>String(x.id)!==b.dataset.delPlan);save();renderSettingsLists();renderAll()});$$('[data-del-annual]').forEach(b=>b.onclick=()=>{S.annual=S.annual.filter(x=>String(x.id)!==b.dataset.delAnnual);save();renderSettingsLists();renderAll()})}
function addBudget(type){const name=prompt(type==='plan'?'ชื่อค่าใช้จ่ายประจำ':'ชื่อค่าใช้จ่ายรายปี');if(!name)return;const amt=n(prompt('จำนวนเงิน (บาท)')||0);if(amt<=0)return alert('กรุณาใส่จำนวนมากกว่า 0');(type==='plan'?S.plans:S.annual).push({id:id(),name:String(name).trim(),amount:amt});save();renderSettingsLists();renderAll()}
function saveSettings(){S.profile={...S.profile,name:$('#sName').value.trim(),income:n($('#sIncome').value),saving:n($('#sSaving').value),emerTarget:Math.max(1,n($('#sEmerTarget').value)||6),initialized:true};save();localStorage.setItem(FIRST,'1');settings(false);renderAll();toast('✓ บันทึกการตั้งค่าแล้ว')}
function backup(){const blob=new Blob([JSON.stringify(S,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`M-Personal-Finance-${todayISO()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function restore(file){if(!file)return;const r=new FileReader();r.onload=()=>{try{S=normalize(JSON.parse(r.result));window.S=S;save();renderAll();settings(true);toast('✓ กู้คืนข้อมูลแล้ว')}catch(e){alert('ไฟล์ไม่ถูกต้อง')}};r.readAsText(file)}
let calcExp='';function calcEval(){const clean=calcExp.replace(/×/g,'*').replace(/÷/g,'/');if(!clean||!/^[0-9+\-*/.() ]+$/.test(clean))return null;try{const v=Function('"use strict";return ('+clean+')')();return Number.isFinite(v)?v:null}catch(e){return null}}
function calcPaint(){setText('#calcDisplay',calcExp||'0');const v=calcEval();setText('#calcResult',v===null?'':'= '+v.toLocaleString('th-TH',{maximumFractionDigits:2}))}
function openCalc(){calcExp='';const keys=['C','⌫','÷','×','7','8','9','-','4','5','6','+','1','2','3','.','0','00','(',')','='];$('#calcKeys').innerHTML=keys.map(k=>`<button class="calc-key ${/[÷×+\-]/.test(k)?'op':''} ${k==='='?'equal':''}" data-key="${k}" type="button">${k}</button>`).join('')+'<button class="calc-key calc-use" data-key="use" type="button">ใช้ยอดนี้</button>';$('#calcKeys').querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>{const k=b.dataset.key,v=calcEval();if(k==='C')calcExp='';else if(k==='⌫')calcExp=calcExp.slice(0,-1);else if(k==='='){if(v!==null)calcExp=String(v)}else if(k==='use'){if(v!==null){$('#qAmt').value=comma(v);visible('#calcModal',false)}return}else calcExp+=k;calcPaint()});calcPaint();visible('#calcModal',true)}
let deferredPrompt=null;function installPWA(){const help=$('#mpfInstallHelp');if(deferredPrompt){deferredPrompt.prompt();deferredPrompt.userChoice.then(r=>{if(r.outcome==='accepted')$('#mpfInstallCard').style.display='none';deferredPrompt=null});return}help.classList.add('show');help.innerHTML=/iphone|ipad|ipod/i.test(navigator.userAgent)?'บน iPhone/iPad ให้เปิดด้วย <b>Safari</b> → แชร์ → <b>เพิ่มไปยังหน้าจอโฮม</b>':'ถ้าหน้าติดตั้งยังไม่เด้ง ให้แตะเมนูเบราว์เซอร์ <b>⋮</b> → <b>ติดตั้งแอป</b> หรือ <b>เพิ่มไปยังหน้าจอหลัก</b>'}
function firstStart(){const fresh=!S.profile.initialized&&!S.plans.length&&!S.annual.length&&!S.assets.length&&!S.debts.length&&!S.goals.length&&!S.tx.length&&!localStorage.getItem(FIRST);visible('#mpfFirstStart',fresh)}
function renderAll(){renderDashboard();renderRecent();renderHistory();renderPosition();renderFuture()}
function bind(){bindMoney(document);$$('.tabs button').forEach(b=>b.onclick=()=>go(b.dataset.p));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#fab').onclick=()=>go('quick');$('#guideBtn').onclick=()=>visible('#guide',true);$('#settingsBtn').onclick=()=>settings(true);$$('[data-close]').forEach(b=>b.onclick=()=>visible('#'+b.dataset.close,false));$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m&&m.id!=='mpfFirstStart')visible(m,false)}));$('#eBtn').onclick=()=>{qtype='expense';paintType()};$('#iBtn').onclick=()=>{qtype='income';paintType()};$('#qAmt').addEventListener('input',()=>{formatMoneyInput($('#qAmt'));dupCheck()});$('#qDate').addEventListener('input',()=>{dateTyping($('#qDate'));dupCheck()});$('#qNote').addEventListener('input',dupCheck);$('#saveTxBtn').onclick=saveTx;$('#calcBtn').onclick=openCalc;$('#monthFold').onclick=()=>{const b=$('#monthBody'),open=b.hidden;b.hidden=!open;$('#monthFold').textContent=open?'▲ ย่อ':'▼ เปิด'};$('#hMonth').onchange=renderHistory;$('#hType').onchange=renderHistory;$('#hSearch').oninput=renderHistory;$$('#histCalTabs button').forEach(b=>b.onclick=()=>showHistMode(b.dataset.hist));$('#hcPrev').onclick=()=>{calDate=new Date(calDate.getFullYear(),calDate.getMonth()-1,1);renderCalendar()};$('#hcNext').onclick=()=>{calDate=new Date(calDate.getFullYear(),calDate.getMonth()+1,1);renderCalendar()};$('#addAssetBtn').onclick=()=>openPE('asset');$('#addDebtBtn').onclick=()=>openPE('debt');$('#addGoalBtn').onclick=()=>openGoal();$('#saveGoalBtn').onclick=saveGoal;$('#wfGoal').onchange=e=>{if(e.target.value)useGoal(e.target.value)};['wfPrice','wfCash','wfLoan'].forEach(i=>$('#'+i).addEventListener('input',()=>{formatMoneyInput($('#'+i));futureCalc()}));['wfYears','wfRate','wfType'].forEach(i=>$('#'+i).addEventListener('input',futureCalc));$$('[data-fold]').forEach(b=>b.onclick=()=>{const el=$('#'+b.dataset.fold),open=el.hidden;el.hidden=!open;b.textContent=open?'▲ ย่อ':'▼ เปิดดู'});$('#addPlanBtn').onclick=()=>addBudget('plan');$('#addAnnualBtn').onclick=()=>addBudget('annual');$('#saveSettingsBtn').onclick=saveSettings;$('#backupBtn').onclick=backup;$('#restore').onchange=e=>restore(e.target.files[0]);$('#firstStartSettingsBtn').onclick=()=>{localStorage.setItem(FIRST,'1');visible('#mpfFirstStart',false);settings(true)};$('#mpfInstallBtn').onclick=installPWA;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e});window.addEventListener('appinstalled',()=>$('#mpfInstallCard').style.display='none')}
function init(){bind();$('#qDate').value=isoToThai(todayISO());$('#hMonth').value=todayISO().slice(0,7);paintType();const last=localStorage.getItem('mpf_last_page_v1');if(['dash','quick','hist','position','future'].includes(last))go(last);renderAll();firstStart();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();