(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const num=v=>{const x=Number(String(v??'').replace(/,/g,''));return Number.isFinite(x)?x:0};
const money=v=>'฿'+Math.round(num(v)).toLocaleString('th-TH');
const comma=v=>num(v)?num(v).toLocaleString('en-US',{maximumFractionDigits:2}):'';
function ensureQuickCalendar(){const q=$('#qDate');if(!q)return;const existing=$('.clean-date-row .clean-cal-btn');if(existing){existing.id='qCalendarBtn';$$('.clean-date-row .clean-cal-btn').slice(1).forEach(x=>x.remove());$$('#qNativeDate').slice(1).forEach(x=>x.remove());return}if($('#qCalendarBtn'))return;const holder=document.createElement('div');holder.className='clean-date-row';q.parentNode.insertBefore(holder,q);holder.appendChild(q);const b=document.createElement('button');b.type='button';b.id='qCalendarBtn';b.className='btn soft clean-cal-btn';b.textContent='📅 ปฏิทิน';holder.appendChild(b);let n=$('#qNativeDate');if(!n){n=document.createElement('input');n.type='date';n.id='qNativeDate';n.className='clean-native-date';holder.appendChild(n)}const toIso=v=>{const m=String(v||'').match(/^(\d{2})\/(\d{2})\/(\d{4})$/);return m?`${m[3]}-${m[2]}-${m[1]}`:''};const toTh=v=>{const m=String(v||'').match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?`${m[3]}/${m[2]}/${m[1]}`:''};b.onclick=()=>{n.value=toIso(q.value)||new Date().toISOString().slice(0,10);if(typeof n.showPicker==='function')n.showPicker();else n.click()};n.onchange=()=>{q.value=toTh(n.value);q.dispatchEvent(new Event('input',{bubbles:true}));q.dispatchEvent(new Event('change',{bubbles:true}))}}
function patchQuick(){ensureQuickCalendar();const save=$('#saveTxBtn');if(!save||save.dataset.parity)return;save.dataset.parity='1';const old=save.onclick;save.onclick=e=>{const amt=num($('#qAmt').value),m=$('#qDate').value.match(/^(\d{2})\/(\d{2})\/(\d{4})$/),date=m?`${m[3]}-${m[2]}-${m[1]}`:'',cat=$('#qCat').value,note=$('#qNote').value.trim(),type=$('#eBtn').classList.contains('danger')?'expense':'income';const dup=date&&amt&&(window.S?.tx||[]).some(x=>x.type===type&&x.date===date&&num(x.amount)===amt&&x.cat===cat&&String(x.note||'').trim()===note);if(dup&&!confirm(`พบรายการเหมือนกันแล้ว ${cat} ${money(amt)} วันที่ ${$('#qDate').value}\nต้องการบันทึกซ้ำจริงหรือไม่?`))return;if(old)old.call(save,e);setTimeout(()=>window.go?.('dash'),20)}}
function patchPosition(){const assets=$('#assets'),debts=$('#debts');if(!assets||!debts)return;window.renderPositionParity=function(){if(!window.S)return;assets.innerHTML=S.assets.length?S.assets.map((x,i)=>`<div class="item"><input value="${String(x.name||'').replace(/"/g,'&quot;')}" data-a-name="${i}"><div class="grid g2"><input class="money" value="${comma(x.value)}" data-a-value="${i}"><select data-a-kind="${i}"><option ${x.kind==='พร้อมใช้'?'selected':''}>พร้อมใช้</option><option ${x.kind==='ลงทุน'?'selected':''}>ลงทุน</option><option ${x.kind==='Emergency'?'selected':''}>Emergency</option><option ${x.kind==='เกษียณ'?'selected':''}>เกษียณ</option><option ${x.kind==='ทรัพย์สินอื่น'?'selected':''}>ทรัพย์สินอื่น</option></select></div><button class="btn danger" data-a-del="${i}">ลบ</button></div>`).join(''):'<div class="sub">ยังไม่มีทรัพย์สิน</div>';debts.innerHTML=S.debts.length?S.debts.map((x,i)=>`<div class="item"><input value="${String(x.name||'').replace(/"/g,'&quot;')}" data-d-name="${i}"><div class="grid g2"><label>ยอดคงเหลือ<input class="money" value="${comma(x.balance)}" data-d-bal="${i}"></label><label>ค่างวด/เดือน<input class="money" value="${comma(x.payment)}" data-d-pay="${i}"></label></div><label>ดอกเบี้ยต่อปี (%)<input type="number" step="0.01" value="${num(x.rate)}" data-d-rate="${i}"></label><button class="btn danger" data-d-del="${i}">ลบ</button></div>`).join(''):'<div class="sub">ยังไม่มีหนี้</div>';$$('[data-a-name]').forEach(e=>e.onchange=()=>{S.assets[+e.dataset.aName].name=e.value;saveAndRender()});$$('[data-a-value]').forEach(e=>e.onchange=()=>{S.assets[+e.dataset.aValue].value=num(e.value);saveAndRender()});$$('[data-a-kind]').forEach(e=>e.onchange=()=>{S.assets[+e.dataset.aKind].kind=e.value;saveAndRender()});$$('[data-a-del]').forEach(e=>e.onclick=()=>{S.assets.splice(+e.dataset.aDel,1);saveAndRender()});$$('[data-d-name]').forEach(e=>e.onchange=()=>{S.debts[+e.dataset.dName].name=e.value;saveAndRender()});$$('[data-d-bal]').forEach(e=>e.onchange=()=>{S.debts[+e.dataset.dBal].balance=num(e.value);saveAndRender()});$$('[data-d-pay]').forEach(e=>e.onchange=()=>{S.debts[+e.dataset.dPay].payment=num(e.value);saveAndRender()});$$('[data-d-rate]').forEach(e=>e.onchange=()=>{S.debts[+e.dataset.dRate].rate=num(e.value);saveAndRender()});$$('[data-d-del]').forEach(e=>e.onclick=()=>{S.debts.splice(+e.dataset.dDel,1);saveAndRender()})};function saveAndRender(){localStorage.setItem('spfm_public_v1',JSON.stringify(S));window.renderPositionParity()};setTimeout(window.renderPositionParity,0);$('#peSave')?.addEventListener('click',()=>setTimeout(window.renderPositionParity,30))}
function patchSettings(){const s=$('#settings');if(!s)return;const income=$('#sIncome')?.closest('label');if(income){const n=[...income.childNodes].find(x=>x.nodeType===3&&x.nodeValue.trim());if(n)n.nodeValue='เงินสำหรับใช้จ่าย/เดือน (หลังแยกเงินออมแล้ว)'}const saveBtn=$('#saveSettingsBtn');if(saveBtn)saveBtn.textContent='บันทึกการตั้งค่า';const back=$('#backupBtn');if(back&&!back.dataset.parity){back.dataset.parity='1';const old=back.onclick;back.onclick=e=>{old?.call(back,e);setTimeout(()=>alert('สำรองข้อมูลแล้ว กรุณาเก็บไฟล์นี้ไว้ เผื่อเปลี่ยนเครื่องหรือต้องกู้คืนข้อมูล'),50)}}const restore=$('#restore');if(restore&&!restore.dataset.parity){restore.dataset.parity='1';const old=restore.onchange;restore.onchange=e=>{if(!e.target.files?.[0])return;if(!confirm('กู้คืนข้อมูลจากไฟล์นี้? ข้อมูลปัจจุบันในแอปจะถูกแทนที่ด้วยข้อมูลจากไฟล์สำรอง')){e.target.value='';return}old?.call(restore,e)}}}
function patchFirstStart(){const m=$('#mpfFirstStart');if(!m||m.dataset.parity)return;m.dataset.parity='1';const h=m.querySelector('h2'),sub=m.querySelector('.sub'),btn=$('#firstStartSettingsBtn');if(h)h.textContent='เริ่มต้นที่ “ตั้งค่า”';if(sub)sub.textContent='ก่อนใช้งาน ให้กำหนดเงินสำหรับใช้จ่าย/เดือน เงินออม ค่าใช้จ่ายประจำ และค่าใช้จ่ายรายปี ระบบจะคำนวณเงินที่ควรใช้จริงให้';if(btn)btn.textContent='ไปที่ตั้งค่า';if(!m.querySelector('.later')){const b=document.createElement('button');b.type='button';b.className='btn soft save-wide later';b.textContent='ไว้ก่อน';b.onclick=()=>{localStorage.setItem('mpf_first_start_notice_v1','1');m.classList.remove('on')};btn?.insertAdjacentElement('afterend',b)}}
function preserveUnknownData(){try{const raw=JSON.parse(localStorage.getItem('spfm_public_v1')||'{}');if(!raw||typeof raw!=='object'||!window.S)return;for(const [k,v] of Object.entries(raw))if(!(k in S))S[k]=v}catch{}}
function init(){preserveUnknownData();patchQuick();patchPosition();patchSettings();patchFirstStart();$$('.tabs button').forEach(b=>b.addEventListener('click',()=>setTimeout(()=>{patchQuick();patchPosition();patchSettings();patchFirstStart()},0)));$('#settingsBtn')?.addEventListener('click',()=>setTimeout(patchSettings,0))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,0));else setTimeout(init,0);
})();