(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const num=v=>{const x=Number(String(v??'').replace(/,/g,''));return Number.isFinite(x)?x:0};
const money=v=>'฿'+Math.round(num(v)).toLocaleString('th-TH');
const ymToday=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`};
const ymShift=(ym,d)=>{const m=String(ym||ymToday()).match(/^(\d{4})-(\d{2})$/);const x=m?new Date(+m[1],+m[2]-1+d,1):new Date();return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}`};
const isoToThai=iso=>{const m=String(iso||'').match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?`${m[3]}/${m[2]}/${m[1]}`:''};
const thMonth=ym=>{const m=String(ym||ymToday()).match(/^(\d{4})-(\d{2})$/);return m?new Intl.DateTimeFormat('th-TH',{month:'long',year:'numeric'}).format(new Date(+m[1],+m[2]-1,1)):ym};
const rows=ym=>(window.S?.tx||[]).filter(x=>String(x.date||'').slice(0,7)===ym);
let selected='';
function mountDatePicker(){const q=$('#qDate');if(!q)return;let row=q.closest('.clean-date-row');if(!row){row=document.createElement('div');row.className='clean-date-row';q.parentNode.insertBefore(row,q);row.append(q)}let b=row.querySelector('#qCalendarBtn')||row.querySelector('.clean-cal-btn');if(!b){b=document.createElement('button');b.type='button';b.className='btn soft clean-cal-btn';row.append(b)}b.id='qCalendarBtn';b.textContent='📅 ปฏิทิน';let n=$('#qNativeDate');if(!n){n=document.createElement('input');n.type='date';n.id='qNativeDate';n.className='clean-native-date';row.append(n)}else if(n.parentNode!==row)row.append(n);n.style.cssText='position:fixed!important;left:-10000px!important;top:0!important;width:1px!important;height:1px!important;min-width:0!important;min-height:0!important;padding:0!important;margin:0!important;border:0!important;opacity:0!important;pointer-events:none!important;appearance:none!important;-webkit-appearance:none!important;';$$('.clean-cal-btn').filter(x=>x!==b).forEach(x=>x.remove());$$('#qNativeDate').filter(x=>x!==n).forEach(x=>x.remove());const toIso=v=>{const m=String(v||'').match(/^(\d{2})\/(\d{2})\/(\d{4})$/);return m?`${m[3]}-${m[2]}-${m[1]}`:''};b.onclick=()=>{n.value=toIso(q.value)||new Date().toISOString().slice(0,10);typeof n.showPicker==='function'?n.showPicker():n.click()};n.onchange=()=>{q.value=isoToThai(n.value);q.dispatchEvent(new Event('input',{bubbles:true}));q.dispatchEvent(new Event('change',{bubbles:true}))};const lab=q.closest('label');if(lab){const t=[...lab.childNodes].find(x=>x.nodeType===3&&x.nodeValue.trim());if(t)t.nodeValue='วันที่ '}}
function ensureAnalysisControls(){const wrap=$('#histAnalysisWrap');if(!wrap||$('#haFilters'))return;const c=document.createElement('div');c.className='card';c.id='haFilters';c.innerHTML='<h2>ประวัติรายการทั้งหมด</h2><div class="quick-filters"><label>เดือน<input id="haMonth" type="month"></label><label>ประเภท<select id="haType"><option value="all">ทั้งหมด</option><option value="expense">ค่าใช้จ่าย</option><option value="income">รายรับ</option></select></label><label>หมวด<select id="haCat"><option value="all">ทุกหมวด</option></select></label></div><div class="grid g2"><div class="row"><span>รายรับ</span><b id="haInc">฿0</b></div><div class="row"><span>ค่าใช้จ่าย</span><b id="haExp">฿0</b></div></div><div class="hist-summary-only">หน้านี้แสดงเฉพาะสรุปและกราฟ รายการแต่ละรายการดูได้ที่ “บันทึก” ในรายการรายเดือน</div>';wrap.prepend(c);['haMonth','haType','haCat'].forEach(id=>$('#'+id).addEventListener('change',paintAnalysis));$('#haMonth').value=$('#hMonth').value||ymToday()}
function paintDay(iso){selected=iso;$$('#calendarGrid .hc-day').forEach(b=>b.classList.toggle('sel',b.dataset.date===iso));const r=(window.S?.tx||[]).filter(x=>x.date===iso),root=$('#hcDetail');if(!root)return;const exp=r.filter(x=>x.type==='expense').reduce((a,x)=>a+num(x.amount),0);root.innerHTML=`<div class="hc-detail-head"><div><b>${isoToThai(iso)}</b><div class="sub">${r.length?r.length+' รายการ':'ไม่มีรายการ'}</div></div>${exp?`<b class="status-bad">${money(exp)}</b>`:''}</div>`+r.map(x=>`<div class="item"><div class="section-head"><span><b>${x.note||x.cat||'รายการ'}</b><div class="sub">${x.cat||''}</div></span><b class="${x.type==='expense'?'status-bad':'status-good'}">${x.type==='expense'?'-':'+'}${money(x.amount)}</b></div></div>`).join('')}
function paintCalendar(){const h=$('#hMonth');if(!h)return;const ym=h.value||ymToday();h.value=ym;const [y,m]=ym.split('-').map(Number),days=new Date(y,m,0).getDate(),start=new Date(y,m-1,1).getDay(),r=rows(ym),exp={};r.filter(x=>x.type==='expense').forEach(x=>exp[x.date]=(exp[x.date]||0)+num(x.amount));$('#hcTitle').textContent=thMonth(ym);$('#hcTotal').textContent=money(Object.values(exp).reduce((a,b)=>a+b,0));let html='';for(let i=0;i<start;i++)html+='<div></div>';for(let d=1;d<=days;d++){const iso=`${ym}-${String(d).padStart(2,'0')}`,has=r.some(x=>x.date===iso);html+=`<button type="button" class="hc-day ${selected===iso?'sel':''}" data-date="${iso}"><span class="hc-num">${d}</span>${has?'<span class="hc-dot"></span>':''}${exp[iso]?`<span class="hc-amt">${money(exp[iso])}</span>`:''}</button>`}$('#calendarGrid').innerHTML=html;$('#calendarGrid').querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>paintDay(b.dataset.date));if(!selected.startsWith(ym)){const now=new Date(),d=(now.getFullYear()===y&&now.getMonth()+1===m)?Math.min(now.getDate(),days):Math.min(now.getDate(),days);selected=`${ym}-${String(d).padStart(2,'0')}`}paintDay(selected)}
function cats(){return [...new Set((window.S?.tx||[]).map(x=>x.cat).filter(Boolean))]}
function paintAnalysis(){ensureAnalysisControls();const h=$('#hMonth'),hm=$('#haMonth');const ym=(hm?.value||h?.value||ymToday());if(h&&h.value!==ym)h.value=ym;const type=$('#haType')?.value||'all',cat=$('#haCat')?.value||'all',sel=$('#haCat');if(sel){const keep=sel.value;sel.innerHTML='<option value="all">ทุกหมวด</option>'+cats().map(c=>`<option>${c}</option>`).join('');if([...sel.options].some(o=>o.value===keep))sel.value=keep}const filtered=rows(ym).filter(x=>(type==='all'||x.type===type)&&(cat==='all'||x.cat===cat));$('#haInc').textContent=money(filtered.filter(x=>x.type==='income').reduce((a,x)=>a+num(x.amount),0));$('#haExp').textContent=money(filtered.filter(x=>x.type==='expense').reduce((a,x)=>a+num(x.amount),0));const map={};filtered.filter(x=>x.type==='expense').forEach(x=>map[x.cat||'ไม่ระบุหมวด']=(map[x.cat||'ไม่ระบุหมวด']||0)+num(x.amount));const e=Object.entries(map).sort((a,b)=>b[1]-a[1]),total=e.reduce((a,x)=>a+x[1],0),colors=['#fb7185','#38bdf8','#fbbf24','#34d399','#818cf8','#f472b6','#22c55e','#fb923c'];let pos=0,stops=[];e.forEach((r,i)=>{const s=pos;pos+=total?r[1]/total*100:0;stops.push(`${colors[i%colors.length]} ${s}% ${pos}%`)});$('#histDonut').style.background=stops.length?`conic-gradient(${stops.join(',')})`:'#e5e7eb';const hole=$('#histDonut .hist-donut-hole');if(hole)hole.innerHTML=`<div><small>รวม</small><b>${money(total)}</b></div>`;$('#histLegend').innerHTML=e.length?e.map((r,i)=>`<div class="legend-row"><span class="legend-dot" style="background:${colors[i%colors.length]}"></span><span>${r[0]}</span><b>${total?(r[1]/total*100).toFixed(1):0}%</b></div>`).join(''):'ยังไม่มีค่าใช้จ่ายในเดือนที่เลือก';$('#top3').innerHTML=e.slice(0,3).map((r,i)=>`<div class="row"><span>${i+1}. ${r[0]}</span><b>${money(r[1])}</b></div>`).join('')||'<div class="sub">ยังไม่มีข้อมูล</div>';const now=new Date(),trend=[];for(let i=11;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1),k=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`,v=rows(k).filter(x=>x.type==='expense').reduce((a,x)=>a+num(x.amount),0);trend.push({label:new Intl.DateTimeFormat('th-TH',{month:'short'}).format(d),v})}const max=Math.max(1,...trend.map(x=>x.v));$('#trendBars').innerHTML=trend.map(x=>`<div class="trend-col"><span>${x.v?Math.round(x.v/1000)+'K':''}</span><i style="height:${Math.max(2,x.v/max*100)}%"></i><small>${x.label}</small></div>`).join('')}
function repaint(){paintCalendar();paintAnalysis()}
function bind(){mountDatePicker();ensureAnalysisControls();const h=$('#hMonth');h.value=h.value||ymToday();$('#hcPrev').onclick=()=>{h.value=ymShift(h.value,-1);if($('#haMonth'))$('#haMonth').value=h.value;selected='';repaint()};$('#hcNext').onclick=()=>{h.value=ymShift(h.value,1);if($('#haMonth'))$('#haMonth').value=h.value;selected='';repaint()};h.onchange=()=>{if($('#haMonth'))$('#haMonth').value=h.value;selected='';repaint()};$$('#histCalTabs button').forEach(b=>b.addEventListener('click',()=>setTimeout(repaint,0)));$('#saveTxBtn')?.addEventListener('click',()=>setTimeout(repaint,30));repaint()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(bind,0));else setTimeout(bind,0);
})();