(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const num=v=>{const x=Number(String(v??'').replace(/,/g,''));return Number.isFinite(x)?x:0};
const money=v=>'฿'+Math.round(num(v)).toLocaleString('th-TH');
const ymToday=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`};
const ymShift=(ym,delta)=>{const m=String(ym||ymToday()).match(/^(\d{4})-(\d{2})$/);if(!m)return ymToday();const d=new Date(Number(m[1]),Number(m[2])-1+delta,1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`};
const isoToThai=iso=>{const m=String(iso||'').match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?`${m[3]}/${m[2]}/${m[1]}`:''};
const thMonth=ym=>{const m=String(ym||ymToday()).match(/^(\d{4})-(\d{2})$/);return m?new Intl.DateTimeFormat('th-TH',{month:'long',year:'numeric'}).format(new Date(Number(m[1]),Number(m[2])-1,1)):ym};
const monthRows=ym=>(window.S&&Array.isArray(S.tx)?S.tx:[]).filter(x=>String(x.date||'').slice(0,7)===ym);
function style(){if($('#cleanHistoryFixCss'))return;const s=document.createElement('style');s.id='cleanHistoryFixCss';s.textContent=`
.clean-date-row{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center;position:relative}.clean-date-row #qDate{margin-top:5px}.clean-cal-btn{min-height:50px;margin-top:5px;white-space:nowrap}.clean-native-date{position:absolute!important;opacity:0!important;width:1px!important;height:1px!important;right:0!important;bottom:0!important;pointer-events:none!important}.hist-donut-hole small{display:block}.hc-day.sel{background:#f3e8d5;box-shadow:inset 0 0 0 1.5px #b58a45}.hc-detail .item{margin-top:6px}
`;document.head.appendChild(s)}
function mountQuickCalendar(){const q=$('#qDate');if(!q||$('#qNativeDate'))return;const label=q.closest('label');if(!label)return;const row=document.createElement('div');row.className='clean-date-row';q.parentNode.insertBefore(row,q);row.appendChild(q);const btn=document.createElement('button');btn.type='button';btn.className='btn soft clean-cal-btn';btn.id='qCalendarBtn';btn.textContent='📅 ปฏิทิน';row.appendChild(btn);const native=document.createElement('input');native.type='date';native.id='qNativeDate';native.className='clean-native-date';row.appendChild(native);const toIso=v=>{const m=String(v||'').match(/^(\d{2})\/(\d{2})\/(\d{4})$/);return m?`${m[3]}-${m[2]}-${m[1]}`:''};btn.onclick=()=>{native.value=toIso(q.value)||new Date().toISOString().slice(0,10);if(typeof native.showPicker==='function')native.showPicker();else native.click()};native.onchange=()=>{q.value=isoToThai(native.value);q.dispatchEvent(new Event('input',{bubbles:true}));q.dispatchEvent(new Event('change',{bubbles:true}))};}
let selectedDate='';
function paintDay(iso){selectedDate=iso;$$('#calendarGrid .hc-day').forEach(b=>b.classList.toggle('sel',b.dataset.date===iso));const rows=(window.S?.tx||[]).filter(x=>x.date===iso),root=$('#hcDetail');if(!root)return;root.innerHTML=`<div class="hc-detail-head"><div><b>${isoToThai(iso)}</b><div class="sub">${rows.length?rows.length+' รายการ':'ไม่มีรายการ'}</div></div></div>`+(rows.length?rows.map(x=>`<div class="item"><div class="section-head"><span><b>${String(x.note||x.cat||'รายการ')}</b><div class="sub">${String(x.cat||'')}</div></span><b class="${x.type==='expense'?'status-bad':'status-good'}">${x.type==='expense'?'-':'+'}${money(x.amount)}</b></div></div>`).join(''):'');}
function paintCalendar(){const h=$('#hMonth');if(!h)return;const ym=h.value||ymToday();if(!h.value)h.value=ym;const [y,m]=ym.split('-').map(Number),first=new Date(y,m-1,1),days=new Date(y,m,0).getDate(),start=first.getDay(),rows=monthRows(ym),exp={};rows.filter(x=>x.type==='expense').forEach(x=>exp[x.date]=(exp[x.date]||0)+num(x.amount));$('#hcTitle').textContent=thMonth(ym);$('#hcTotal').textContent=money(Object.values(exp).reduce((a,b)=>a+b,0));let html='';for(let i=0;i<start;i++)html+='<div></div>';for(let d=1;d<=days;d++){const iso=`${ym}-${String(d).padStart(2,'0')}`,has=rows.some(x=>x.date===iso);html+=`<button type="button" class="hc-day ${selectedDate===iso?'sel':''}" data-date="${iso}"><span class="hc-num">${d}</span>${has?'<span class="hc-dot"></span>':''}${exp[iso]?`<span class="hc-amt">${money(exp[iso])}</span>`:''}</button>`}$('#calendarGrid').innerHTML=html;$('#calendarGrid').querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>paintDay(b.dataset.date));if(!selectedDate.startsWith(ym)){const today=new Date(),d=(today.getFullYear()===y&&today.getMonth()+1===m)?Math.min(today.getDate(),days):1;selectedDate=`${ym}-${String(d).padStart(2,'0')}`;}paintDay(selectedDate)}
function paintAnalysis(){const h=$('#hMonth');if(!h)return;const ym=h.value||ymToday(),rows=monthRows(ym).filter(x=>x.type==='expense'),map={};rows.forEach(x=>map[x.cat||'อื่น ๆ']=(map[x.cat||'อื่น ๆ']||0)+num(x.amount));const entries=Object.entries(map).sort((a,b)=>b[1]-a[1]),total=entries.reduce((a,x)=>a+x[1],0),colors=['#b58a45','#79654a','#b9a488','#8c765b','#d0b98f','#6d5d4b','#c99764','#9c8b79'];let pos=0,stops=[];entries.forEach((r,i)=>{const s=pos;pos+=total?r[1]/total*100:0;stops.push(`${colors[i%colors.length]} ${s}% ${pos}%`)});const donut=$('#histDonut');if(donut)donut.style.background=stops.length?`conic-gradient(${stops.join(',')})`:'#ede6dc';const hole=donut?.querySelector('.hist-donut-hole');if(hole)hole.innerHTML=`<div><small>${thMonth(ym)}</small><b>Actual</b></div>`;const legend=$('#histLegend');if(legend)legend.innerHTML=entries.length?entries.map((r,i)=>`<div class="legend-row"><span class="legend-dot" style="background:${colors[i%colors.length]}"></span><span>${r[0]}</span><b>${total?(r[1]/total*100).toFixed(1):'0.0'}%</b></div>`).join(''):`ยังไม่มีค่าใช้จ่ายใน ${thMonth(ym)}`;const top=$('#top3');if(top)top.innerHTML=entries.slice(0,3).map((r,i)=>`<div class="row"><span>${i+1}. ${r[0]}</span><b>${money(r[1])}</b></div>`).join('')||'<div class="sub">ยังไม่มีข้อมูล</div>';}
function repaint(){paintCalendar();paintAnalysis()}
function bindHistory(){const h=$('#hMonth'),prev=$('#hcPrev'),next=$('#hcNext');if(!h||!prev||!next)return;prev.onclick=()=>{h.value=ymShift(h.value,-1);selectedDate='';h.dispatchEvent(new Event('change',{bubbles:true}));setTimeout(repaint,0)};next.onclick=()=>{h.value=ymShift(h.value,1);selectedDate='';h.dispatchEvent(new Event('change',{bubbles:true}));setTimeout(repaint,0)};h.addEventListener('change',()=>{selectedDate='';setTimeout(repaint,0)});$$('#histCalTabs button').forEach(b=>b.addEventListener('click',()=>setTimeout(repaint,0)));const save=$('#saveTxBtn');if(save)save.addEventListener('click',()=>setTimeout(repaint,20));}
function init(){style();mountQuickCalendar();bindHistory();repaint()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,0));else setTimeout(init,0);
})();