// Easier Money/Assets/Debts entry + collapsible detail cards. Keeps existing data/schema.
(function(){
 const K='spfm_ui_position_easy_v1';
 const A=[['💵','เงินสด / เงินฝาก','พร้อมใช้'],['📈','หุ้น / กองทุน / เงินลงทุน','ลงทุน'],['🪙','ทอง / สลาก / พันธบัตร','ลงทุน'],['🏠','บ้าน / คอนโด / ที่ดิน','ทรัพย์สิน'],['🚗','รถ','ทรัพย์สิน'],['📦','ทรัพย์สินอื่น','ทรัพย์สิน']];
 const D=[['🏠','หนี้บ้าน'],['🚗','หนี้รถ'],['💳','บัตรเครดิต / สินเชื่อ'],['📄','หนี้อื่น']];
 function n(v){return Number(String(v==null?'':v).replace(/,/g,''))||0}
 function money(v){return typeof fm==='function'?fm(v):'฿'+n(v).toLocaleString('th-TH')}
 function state(){try{return JSON.parse(localStorage.getItem(K)||'{}')}catch(e){return{}}}
 function setState(k,v){let s=state();s[k]=v;localStorage.setItem(K,JSON.stringify(s))}
 function css(){if(document.getElementById('posEasyCss'))return;let s=document.createElement('style');s.id='posEasyCss';s.textContent=`.pe-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:11px}.pe-kpi{background:#fff;border:1px solid #e5e7eb;border-radius:14px;padding:12px}.pe-kpi small{display:block;color:#6b7280}.pe-kpi b{display:block;font-size:18px;margin-top:4px}.pe-actions{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-bottom:11px}.pe-big{padding:13px!important;font-size:14px}.pe-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:9px}.pe-choice{border:1px solid #dbe3ea;background:#fff;border-radius:13px;padding:13px;text-align:left;font-weight:800;color:var(--n)}.pe-choice span{font-size:22px;display:block;margin-bottom:5px}.pe-modal{position:fixed;inset:0;background:#0007;z-index:160;display:flex;align-items:flex-end}.pe-sheet{background:#fff;width:min(720px,100%);max-height:92vh;overflow:auto;border-radius:20px 20px 0 0;padding:16px}.pe-field{display:block;margin-top:10px}.pe-section{margin-top:12px;padding-top:10px;border-top:1px solid #e5e7eb}.pe-fold{margin-left:auto;white-space:nowrap}.pe-card-head{display:flex;align-items:center;gap:8px}.pe-card-head h2{margin:0}.pe-collapsed{padding-bottom:14px!important}.pe-collapsed>.pe-detail-body{display:none!important}@media(max-width:520px){.pe-summary{grid-template-columns:1fr}.pe-actions{grid-template-columns:1fr 1fr}}`;document.head.appendChild(s)}
 function totals(){let at=(S.assets||[]).reduce((s,x)=>s+n(x.value),0),dt=(S.debts||[]).reduce((s,x)=>s+n(x.balance),0);return{at,dt,net:at-dt}}
 function summary(){let p=document.getElementById('position'),old=document.getElementById('peTop');if(!p)return;if(!old){old=document.createElement('div');old.id='peTop';p.insertBefore(old,p.firstChild)}let t=totals();old.innerHTML=`<div class="pe-summary"><div class="pe-kpi"><small>ทรัพย์สินทั้งหมด</small><b>${money(t.at)}</b></div><div class="pe-kpi"><small>หนี้ทั้งหมด</small><b class="red">${money(t.dt)}</b></div><div class="pe-kpi"><small>มูลค่าทรัพย์สินสุทธิ</small><b>${money(t.net)}</b></div></div><div class="pe-actions"><button class="btn gold pe-big" onclick="peChoose('asset')">＋ เพิ่มเงิน / ทรัพย์สิน</button><button class="btn ghost pe-big" onclick="peChoose('debt')">＋ เพิ่มหนี้</button></div>`;foldCards()}
 function foldCards(){let p=document.getElementById('position');if(!p)return;let cards=p.querySelectorAll(':scope > .grid > .card'),st=state();cards.forEach((c,i)=>{let oldHead=c.querySelector('.itemtop'),h=oldHead&&oldHead.querySelector('h2');if(!h)return;let isDebt=h.textContent.includes('หนี้'),key=isDebt?'debt':'asset';h.textContent=isDebt?'รายละเอียดหนี้สิน':'รายละเอียดเงินและทรัพย์สิน';let add=oldHead.querySelector('button');if(add)add.style.display='none';if(!c.querySelector('.pe-detail-body')){let body=document.createElement('div');body.className='pe-detail-body';while(oldHead.nextSibling)body.appendChild(oldHead.nextSibling);c.appendChild(body)}oldHead.classList.add('pe-card-head');let btn=oldHead.querySelector('.pe-fold');if(!btn){btn=document.createElement('button');btn.className='btn ghost pe-fold';oldHead.appendChild(btn)}let open=st[key]===true;c.classList.toggle('pe-collapsed',!open);btn.textContent=open?'▲ ย่อ':'▼ เปิดดู';btn.onclick=function(){let now=c.classList.contains('pe-collapsed');c.classList.toggle('pe-collapsed',!now);btn.textContent=now?'▲ ย่อ':'▼ เปิดดู';setState(key,now)}})}
 function modal(html){peClose();let m=document.createElement('div');m.id='peModal';m.className='pe-modal';m.onclick=e=>{if(e.target===m)peClose()};m.innerHTML='<div class="pe-sheet">'+html+'</div>';document.body.appendChild(m)}
 window.peClose=()=>document.getElementById('peModal')?.remove();
 window.peChoose=function(type){let rows=type==='asset'?A:D;modal(`<div class="itemtop"><div><h2>${type==='asset'?'เพิ่มเงิน / ทรัพย์สิน':'เพิ่มหนี้'}</h2><div class="sub">เลือกประเภทก่อน ระบบจะถามเฉพาะข้อมูลที่จำเป็น</div></div><button class="btn ghost" onclick="peClose()">ปิด</button></div><div class="pe-grid" style="margin-top:12px">${rows.map((r,i)=>`<button class="pe-choice" onclick="peForm('${type}',${i})"><span>${r[0]}</span>${r[1]}</button>`).join('')}</div>`)};
 window.peForm=function(type,i){if(type==='asset'){let r=A[i];modal(`<div class="itemtop"><h2>${r[0]} ${r[1]}</h2><button class="btn ghost" onclick="peClose()">ปิด</button></div><label class="pe-field">ชื่อรายการ<input id="peName" placeholder="เช่น SCB ออมทรัพย์ / บ้าน / รถ"></label><label class="pe-field">มูลค่าปัจจุบันโดยประมาณ (บาท)<input id="peValue" class="money" inputmode="decimal" placeholder="0"></label>${i===3||i===4?`<div class="pe-section"><label><input id="peHasDebt" type="checkbox" style="width:auto" onchange="document.getElementById('peDebtFields').style.display=this.checked?'block':'none'"> รายการนี้ยังมีหนี้อยู่</label><div id="peDebtFields" style="display:none"><label class="pe-field">ยอดหนี้คงเหลือ<input id="peBalance" class="money" inputmode="decimal" placeholder="0"></label><label class="pe-field">ค่างวดต่อเดือน<input id="pePayment" class="money" inputmode="decimal" placeholder="0"></label></div></div>`:''}<button class="btn navy" style="width:100%;margin-top:14px" onclick="peSaveAsset(${i})">บันทึก</button>`)}else{let r=D[i];modal(`<div class="itemtop"><h2>${r[0]} ${r[1]}</h2><button class="btn ghost" onclick="peClose()">ปิด</button></div><label class="pe-field">ชื่อหนี้<input id="peName" placeholder="เช่น บ้าน / รถ / บัตรเครดิต"></label><label class="pe-field">ยอดหนี้คงเหลือ<input id="peBalance" class="money" inputmode="decimal" placeholder="0"></label><label class="pe-field">ค่างวดต่อเดือน<input id="pePayment" class="money" inputmode="decimal" placeholder="0"></label><button class="btn navy" style="width:100%;margin-top:14px" onclick="peSaveDebt(${i})">บันทึก</button>`)} }
 function persist(){if(typeof save==='function')save();if(typeof render==='function')render();summary();peClose()}
 window.peSaveAsset=function(i){let name=document.getElementById('peName').value.trim(),value=n(document.getElementById('peValue').value);if(!name){alert('กรุณาใส่ชื่อรายการ');return}let r=A[i];S.assets.push({id:Date.now().toString(36),name,value,kind:r[2]});let has=document.getElementById('peHasDebt');if(has&&has.checked){let bal=n(document.getElementById('peBalance').value),pay=n(document.getElementById('pePayment').value);if(bal>0)S.debts.push({id:(Date.now()+1).toString(36),name:'หนี้ '+name,balance:bal,payment:pay})}persist()}
 window.peSaveDebt=function(i){let name=document.getElementById('peName').value.trim(),bal=n(document.getElementById('peBalance').value),pay=n(document.getElementById('pePayment').value);if(!name){alert('กรุณาใส่ชื่อหนี้');return}S.debts.push({id:Date.now().toString(36),name,balance:bal,payment:pay});persist()}
 window.peWizard=function(){modal(`<div class="itemtop"><div><h2>ช่วยฉันกรอกครั้งแรก</h2><div class="sub">ตอบทีละข้อ ไม่ต้องรู้ศัพท์การเงิน</div></div><button class="btn ghost" onclick="peClose()">ปิด</button></div><div id="peW" style="margin-top:12px"></div>`);peWStep(0)};
 const W=[['มีเงินสดหรือเงินในบัญชีธนาคารไหม?',0],['มีหุ้น กองทุน หรือเงินลงทุนไหม?',1],['มีบ้าน คอนโด หรือที่ดินไหม?',3],['มีรถไหม?',4],['มีหนี้อื่น เช่น บัตรเครดิตหรือสินเชื่อไหม?',null]];
 window.peWStep=function(i){let w=document.getElementById('peW');if(!w)return;if(i>=W.length){w.innerHTML='<div class="ok">เรียบร้อยค่ะ ระบบจะรวมทรัพย์สิน หนี้ และคำนวณมูลค่าทรัพย์สินสุทธิให้</div><button class="btn navy" style="width:100%;margin-top:12px" onclick="peClose()">เสร็จ</button>';summary();return}let x=W[i];w.innerHTML=`<h3>${i+1}/${W.length} • ${x[0]}</h3><div class="pe-actions" style="margin-top:12px"><button class="btn gold" onclick="peWYes(${i})">มี</button><button class="btn ghost" onclick="peWStep(${i+1})">ไม่มี / ข้าม</button></div>`}
 window.peWYes=function(i){let x=W[i];if(x[1]===null){peForm('debt',3);return}peForm('asset',x[1])}
 function addWizard(){let top=document.getElementById('peTop');if(!top||document.getElementById('peWizardBtn'))return;let b=document.createElement('button');b.id='peWizardBtn';b.className='btn ghost';b.style.cssText='width:100%;margin:-2px 0 11px';b.textContent='✨ ช่วยฉันกรอกครั้งแรก';b.onclick=peWizard;top.insertAdjacentElement('afterend',b)}
 function apply(){css();summary();addWizard();foldCards()}
 if(typeof render==='function'&&!window.__peWrapped){let base=render;window.render=function(){base();setTimeout(apply,0)};window.__peWrapped=true}apply();
})();