const CACHE='spfm-public-v66-livefix3';
const ASSETS=['./','./index.html','./manifest.webmanifest','./icon-192.svg','./icon-512.svg','./ux-income-label-v35.js','./future-whatif-v1.js','./financial-health-v1.js','./financial-goals-v1.js','./history-insights-v1.js','./history-calendar-v1.js','./quick-guide-fold-v1.js','./health-simple-v1.js','./position-easy-v1.js','./position-visual-v1.js','./settings-fold-v1.js','./quick-guide-copy-v1.js','./moji-theme-fix-v2.js','./moji-ui-skin-v2.js','./commercial-rc1.js','./pwa-install-v1.js','./money-input-format-v1.js','./first-start-settings-v1.js','./persist-page-v1.js','./quick-entry-easy-v1.js','./dashboard-overview-v2.js','./dashboard-goal-sync-v1.js'];
const HEAD_BOOT='<style id="mpfBootTheme">:root{--n:#342d25!important;--g:#b58a45!important;--bg:#f6f1e9!important;--r:#9b4c46!important;--gr:#4e755d!important;--m:#7c756d!important}html,body{background:#f6f1e9!important;color:#342d25!important}body{background:linear-gradient(180deg,#f4efe7 0,#fbfaf7 45%,#f4efe7 100%)!important}header{background:#342d25!important;border-bottom:1px solid #b58a4566!important;color:#fff!important}header .ghost{background:#f8f3eb!important;color:#342d25!important;border:1px solid #e6dccf!important}.card{background:#fffdf9!important;border-color:#e5dccf!important}.navy{background:#342d25!important;color:#fff!important}.gold{background:#b58a45!important;color:#fff!important}.ghost{background:#f1eadf!important;color:#342d25!important}.tabs{background:#fcfaf6!important;border-top-color:#e5dccf!important}.tabs button.on{background:#eee5d8!important;color:#342d25!important}.fab{background:#b58a45!important;color:#fff!important}</style>';
const INJECT='<script src="./ux-income-label-v35.js?v=66"></script><script src="./financial-health-v1.js?v=66"></script><script src="./future-whatif-v1.js?v=66"></script><script src="./financial-goals-v1.js?v=1"></script><script src="./history-insights-v1.js?v=66"></script><script src="./history-calendar-v1.js?v=2"></script><script src="./quick-guide-fold-v1.js?v=66"></script><script src="./health-simple-v1.js?v=66"></script><script src="./position-easy-v1.js?v=66"></script><script src="./position-visual-v1.js?v=2"></script><script src="./settings-fold-v1.js?v=66"></script><script src="./quick-guide-copy-v1.js?v=66"></script><script src="./moji-theme-fix-v2.js?v=66"></script><script src="./moji-ui-skin-v2.js?v=66"></script><script src="./commercial-rc1.js?v=rc1"></script><script src="./pwa-install-v1.js?v=2"></script><script src="./money-input-format-v1.js?v=2"></script><script src="./first-start-settings-v1.js?v=1"></script><script src="./persist-page-v1.js?v=1"></script><script src="./quick-entry-easy-v1.js?v=4"></script><script src="./dashboard-overview-v2.js?v=4"></script><script src="./dashboard-goal-sync-v1.js?v=1"></script>';
function normalizeHead(t){return t.replace('<meta name="theme-color" content="#0b1f33">','<meta name="theme-color" content="#342d25">').replace('<meta name="apple-mobile-web-app-title" content="My Finance">','<meta name="apple-mobile-web-app-title" content="M Personal Finance">').replace('<title>Smart Personal Finance</title>','<title>M Personal Finance</title>').replace('</head>',HEAD_BOOT+'</head>')}
function shell(t,isAndroid){t=normalizeHead(t);return isAndroid?t:t.replace('</body>',INJECT+'</body>')}
function htmlResponse(t){return new Response(t,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store, no-cache, must-revalidate'}})}
self.addEventListener('install',e=>{e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)));self.skipWaiting()});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))));self.clients.claim()});
self.addEventListener('fetch',e=>{
 if(e.request.method!=='GET')return;const u=new URL(e.request.url);
 if(e.request.mode==='navigate'||u.pathname.endsWith('/index.html')||u.pathname.endsWith('/smart-personal-finance/')){
  e.respondWith((async()=>{const isAndroid=u.searchParams.has('android');try{const r=await fetch('./index.html',{cache:'no-store'});if(!r.ok)throw new Error('index '+r.status);return htmlResponse(shell(await r.text(),isAndroid))}catch(err){const r=await caches.match('./index.html');if(!r)return Response.error();return htmlResponse(shell(await r.text(),isAndroid))}})());return
 }
 e.respondWith(fetch(e.request,{cache:'no-store'}).then(r=>{const cp=r.clone();caches.open(CACHE).then(k=>k.put(e.request,cp));return r}).catch(()=>caches.match(e.request)));
});