import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const BASE=process.env.QA_BASE_URL||'http://127.0.0.1:4173/';
const browser=await chromium.launch({headless:true});
const ctx=await browser.newContext({viewport:{width:412,height:915},isMobile:true,hasTouch:true,acceptDownloads:true});
const p=await ctx.newPage();const errors=[];
p.on('pageerror',e=>errors.push('pageerror: '+e.message));p.on('console',m=>{if(m.type()==='error')errors.push('console: '+m.text())});
p.on('dialog',d=>d.accept(d.type()==='prompt'?'QA รายการ':'').catch(()=>{}));
const wait=n=>p.waitForTimeout(n),vis=async s=>p.locator(s).first().isVisible().catch(()=>false);
async function tab(id){const b=p.locator(`.tabs button[data-p="${id}"]`);assert.equal(await b.count(),1,'missing tab '+id);await b.click();await wait(80);assert(await vis('#'+id),id+' not visible')}
async function clean(sel='body'){const t=await p.locator(sel).innerText();assert(!/\bNaN\b|\bInfinity\b|\bundefined\b|null\s*บาท/i.test(t),'bad calculated text '+sel)}
const ymShift=(ym,d)=>{const [y,m]=ym.split('-').map(Number),x=new Date(y,m-1+d,1);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}`};
await p.goto(BASE,{waitUntil:'networkidle'});await wait(250);
assert.equal(await p.locator('text=Smart Personal Finance').count(),0,'legacy title leaked');
assert.equal(await p.locator('text=Quick Guide • เริ่มตรงไหน?').count(),0,'legacy dashboard leaked');
assert.equal(await p.locator('.tabs button').count(),5,'bottom menu must have 5 tabs');
const navSize=await p.locator('.nav-ico svg').first().evaluate(e=>({w:parseFloat(getComputedStyle(e).width),h:parseFloat(getComputedStyle(e).height)}));assert(navSize.w>=24&&navSize.h>=24,'bottom nav icons too small');
assert(await vis('#mpfFirstStart'),'first-start popup missing');assert((await p.locator('#mpfFirstStart').innerText()).includes('เริ่มต้นใช้งาน M Personal Finance'),'first-start copy wrong');
await p.locator('#firstStartSettingsBtn').click();assert(await vis('#settings'));await p.locator('[data-close="settings"]').click();
await p.evaluate(()=>{const x={profile:{name:'QA',income:46000,saving:8000,emerTarget:6,initialized:true},plans:[{id:'p1',name:'ค่าเช่า',amount:9000},{id:'p2',name:'เดินทาง',amount:3000}],annual:[{id:'a1',name:'ประกัน',amount:12000}],assets:[{id:'as1',name:'เงินฝาก',kind:'พร้อมใช้',value:30000},{id:'as2',name:'เงินฉุกเฉิน',kind:'Emergency',value:30000}],debts:[{id:'d1',name:'หนี้บ้าน',balance:400000,payment:5000,rate:4.5}],goals:[{id:'g1',name:'รถใหม่',target:900000,current:150000},{id:'g2',name:'บ้าน',target:5000000,current:250000}],tx:[{id:'t1',type:'expense',amount:1200,cat:'อาหาร',date:new Date().toISOString().slice(0,10),note:'QA'}]};localStorage.setItem('spfm_public_v1',JSON.stringify(x));localStorage.setItem('mpf_first_start_notice_v1','1')});await p.reload({waitUntil:'networkidle'});await wait(250);
for(const id of ['dash','quick','hist','position','future']){await tab(id);await clean('#'+id)}
await tab('dash');const calc=await p.evaluate(()=>({p:plan(),a:ac()}));assert.deepEqual(calc.p,{inc:46000,ex:12000,an:1000,remain:33000});assert.equal(calc.a.total,60000);assert.equal(calc.a.debt,400000);assert.equal(calc.a.net,-340000);const dash=await p.locator('#dash').innerText();for(const x of ['M Personal Finance ช่วยอะไร?','33,000','สุขภาพการเงินของฉัน','เงินสำรองฉุกเฉิน','เป้าหมายการเงิน','รถใหม่','บ้าน'])assert(dash.includes(x),'dashboard missing '+x);assert((await p.locator('#dash .dv2-progress').count())>=3,'dashboard progress missing');assert(await vis('.dv2-hero'),'main-style dashboard hero missing');
await p.locator('#guideBtn').click();assert(await vis('#guide'));await p.locator('[data-close="guide"]').click();
await p.locator('#settingsBtn').click();assert(await vis('#settings'));const st=await p.locator('#settings').innerText();for(const x of ['ตั้งค่าการเงิน','ข้อมูลพื้นฐาน','ค่าใช้จ่ายประจำ / งบต่อเดือน','ค่าใช้จ่ายรายปี','สำรองและกู้คืนข้อมูล','บันทึกการตั้งค่า'])assert(st.includes(x),'settings missing '+x);assert.equal(await p.locator('#settings .modal-head').evaluate(e=>getComputedStyle(e).position),'sticky');await p.locator('#sIncome').fill('123456');await p.locator('#sIncome').dispatchEvent('input');assert.equal(await p.locator('#sIncome').inputValue(),'123,456');const folds=p.locator('#settings .sf-toggle');assert.equal(await folds.count(),2);for(let i=0;i<2;i++){await folds.nth(i).click();await folds.nth(i).click()}const dl=p.waitForEvent('download',{timeout:4000}).catch(()=>null);await p.locator('#backupBtn').click();assert(await dl,'backup missing');assert.equal(await p.locator('#restore').count(),1);await p.locator('[data-close="settings"]').click();
await tab('quick');assert(await vis('#qCatStrip'));assert((await p.locator('#qCatStrip .cat-chip').count())>=5,'category icons missing');assert((await p.locator('#qCatStrip .cat-chip svg').count())>=5,'category SVG icons missing');const catSize=await p.locator('#qCatStrip .cat-chip .ico').first().evaluate(e=>({w:parseFloat(getComputedStyle(e).width),h:parseFloat(getComputedStyle(e).height)}));assert(catSize.w>=50&&catSize.h>=50,'category icon container too small');assert(await vis('#qCalendarBtn'),'quick-entry calendar button missing');await p.locator('#qNativeDate').evaluate((e)=>{e.value='2026-08-15';e.dispatchEvent(new Event('change',{bubbles:true}))});assert.equal(await p.locator('#qDate').inputValue(),'15/08/2026','calendar date did not sync to entry date');await p.locator('#calcBtn').click();assert(await vis('#calcModal'));await p.locator('[data-close="calcModal"]').click();const before=await p.evaluate(()=>S.tx.length);await p.locator('#qAmt').fill('2345');await p.locator('#qAmt').dispatchEvent('input');assert.equal(await p.locator('#qAmt').inputValue(),'2,345');await p.locator('#qCatStrip [data-cat="อาหาร"]').click();await p.locator('#saveTxBtn').click();await wait(100);assert.equal(await p.evaluate(()=>S.tx.length),before+1,'transaction not saved');assert((await p.locator('#recent').innerText()).length>0,'monthly list missing');
await tab('hist');assert.equal(await p.locator('#histCalTabs button').count(),2,'history tabs should match main');await p.locator('[data-hist="calendar"]').click();assert(await vis('#histCalCard'));await p.locator('#hMonth').evaluate((e)=>{e.value='2026-08';e.dispatchEvent(new Event('change',{bubbles:true}))});await wait(80);assert((await p.locator('#hcTitle').innerText()).includes('สิงหาคม'),'history month selection not applied');assert((await p.locator('#hcTotal').innerText()).includes('2,345'),'saved expense not reflected in calendar total');const baseYm=await p.locator('#hMonth').inputValue();await p.locator('#hcPrev').click();await wait(50);assert.equal(await p.locator('#hMonth').inputValue(),ymShift(baseYm,-1),'previous month must move exactly one month');await p.locator('#hcNext').click();await wait(50);assert.equal(await p.locator('#hMonth').inputValue(),baseYm,'next month must move exactly one month');await p.locator('[data-hist="analysis"]').click();await wait(80);assert(await vis('#histAnalysisWrap'));assert(await vis('#histDonut'));const analysis=await p.locator('#histAnalysisWrap').innerText();assert(analysis.includes('อาหาร'),'analysis category missing');assert(analysis.includes('2,345'),'analysis value missing');assert(analysis.includes('สิงหาคม'),'analysis month label must follow selected calendar month');assert.equal(await p.locator('#trendBars .trend-col').count(),12,'12-month trend graph missing');
await tab('position');assert.equal(await p.locator('#pvCard .pv-bar').count(),3,'position graph missing');assert((await p.locator('#pvCard').innerText()).includes('มูลค่าทรัพย์สินสุทธิ'));let na=await p.evaluate(()=>S.assets.length);await p.locator('#addAssetBtn').click();assert(await vis('#peModal'));await p.locator('#peName').fill('บัญชี QA');await p.locator('#peValue').fill('50000');await p.locator('#peSave').click();assert.equal(await p.evaluate(()=>S.assets.length),na+1);let nd=await p.evaluate(()=>S.debts.length);await p.locator('#addDebtBtn').click();await p.locator('#peName').fill('หนี้ QA');await p.locator('#peBalance').fill('100000');await p.locator('#pePayment').fill('5000');await p.locator('#peSave').click();assert.equal(await p.evaluate(()=>S.debts.length),nd+1);
await tab('future');const gl=await p.locator('#goalList').innerText();assert(gl.includes('รถใหม่')&&gl.includes('บ้าน'),'goals missing');await p.locator('#wfGoal').selectOption('g2');assert((await p.locator('#wfPrice').inputValue()).includes(','),'what-if goal sync missing');await p.locator('#wfType').selectOption('prepay');assert(await vis('#wfPrepay'),'prepay mode missing');await p.locator('#wfType').selectOption('car');assert(await vis('#wfNew'),'new-debt what-if mode missing');await p.locator('#addGoalBtn').click();assert(await vis('#mpfGoalModal'));await p.locator('#mpfGoalName').fill('เที่ยวญี่ปุ่น');await p.locator('#mpfGoalTarget').fill('120000');await p.locator('#mpfGoalTarget').dispatchEvent('input');assert.equal(await p.locator('#mpfGoalTarget').inputValue(),'120,000');await p.locator('#mpfGoalCurrent').fill('20000');await p.locator('#saveGoalBtn').click();await tab('dash');assert((await p.locator('#dash').innerText()).includes('เที่ยวญี่ปุ่น'),'goal dashboard sync missing');
assert(await vis('#mpfInstallCard'),'install card missing');await p.locator('#mpfInstallBtn').click();assert(await vis('#mpfInstallHelp'),'install fallback missing');await p.evaluate(()=>{window.__prompt=false;const e=new Event('beforeinstallprompt');Object.defineProperty(e,'prompt',{value:()=>{window.__prompt=true}});Object.defineProperty(e,'userChoice',{value:Promise.resolve({outcome:'accepted'})});window.dispatchEvent(e)});await p.locator('#mpfInstallBtn').click();await wait(50);assert(await p.evaluate(()=>window.__prompt),'install prompt path missing');
const man=await ctx.request.get(new URL('manifest.webmanifest',BASE).toString());assert(man.ok());const manifest=await man.json();assert(String(manifest.name).includes('M Personal Finance')&&manifest.icons?.length>=2,'manifest incomplete');const sw=await ctx.request.get(new URL('service-worker.js',BASE).toString());assert(sw.ok());const swt=await sw.text();assert(swt.includes('clean-app.js')&&swt.includes('clean-history.js'));assert(!/financial-goals-v1|moji-|patch-v|dashboard-overview/.test(swt),'legacy service-worker reference');await clean();if(errors.length){console.error(errors.join('\n'));process.exit(1)}await browser.close();console.log('CLEAN BASELINE ALL-PAGE QA PASS');