import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const BASE=process.env.QA_BASE_URL||'http://127.0.0.1:4173/';
const browser=await chromium.launch({headless:true});const ctx=await browser.newContext({viewport:{width:412,height:915},isMobile:true,hasTouch:true,acceptDownloads:true});const p=await ctx.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});const wait=n=>p.waitForTimeout(n);const vis=async s=>p.locator(s).first().isVisible().catch(()=>false);async function tab(id){await p.locator(`.tabs button[data-p="${id}"]`).click();await wait(80);assert(await vis('#'+id),id+' hidden')}
await p.goto(BASE,{waitUntil:'networkidle'});await wait(200);assert.equal(await p.locator('.tabs button').count(),5);assert(await vis('#mpfFirstStart'));await p.locator('#mpfFirstStart .later').click();
await p.evaluate(()=>{const x={profile:{name:'QA',income:46000,saving:8000,emerTarget:6,initialized:true},plans:[{id:'p1',name:'ค่าเช่า',amount:9000},{id:'p2',name:'เดินทาง',amount:3000}],annual:[{id:'a1',name:'ประกัน',amount:12000}],assets:[{id:'as1',name:'เงินฝาก',kind:'พร้อมใช้',value:30000},{id:'as2',name:'เงินฉุกเฉิน',kind:'Emergency',value:30000}],debts:[{id:'d1',name:'หนี้บ้าน',balance:400000,payment:5000,rate:4.5}],goals:[{id:'g1',name:'รถใหม่',target:900000,current:150000}],tx:[{id:'t1',type:'expense',amount:1200,cat:'อาหาร',date:new Date().toISOString().slice(0,10),note:'QA'}],legacyExtra:{keep:true}};localStorage.setItem('spfm_public_v1',JSON.stringify(x));localStorage.setItem('mpf_first_start_notice_v1','1');localStorage.setItem('spfm_ui_position_easy_v1',JSON.stringify({asset:true,debt:true}))});await p.reload({waitUntil:'networkidle'});await wait(200);
await tab('dash');const calc=await p.evaluate(()=>({p:plan(),a:ac()}));assert.deepEqual(calc.p,{inc:46000,ex:12000,an:1000,remain:33000});assert.equal(calc.a.total,60000);
await p.locator('#settingsBtn').click();assert(await vis('#settings'));const st=await p.locator('#settings').innerText();for(const x of ['ตั้งค่าการเงิน','ข้อมูลพื้นฐาน','เงินสำหรับใช้จ่าย/เดือน (หลังแยกเงินออมแล้ว)','ค่าใช้จ่ายประจำ / งบต่อเดือน','ค่าใช้จ่ายรายปี','สำรองและกู้คืนข้อมูล','ส่งออกและความปลอดภัย','CSV ประวัติรายการ','PDF สรุปรายเดือน','PDF ฐานะการเงิน'])assert(st.includes(x),'settings '+x);assert.equal(await p.locator('#rcExportArea').count(),1,'export area missing');assert.equal(await p.locator('#rcCsvBtn').count(),1);assert.equal(await p.locator('#rcMonthlyBtn').count(),1);assert.equal(await p.locator('#rcPositionBtn').count(),1);const dlPromise=p.waitForEvent('download');await p.locator('#rcCsvBtn').click();const dl=await dlPromise;assert((await dl.suggestedFilename()).endsWith('.csv'),'csv export failed');await p.locator('#sIncome').fill('123456');await p.locator('#sIncome').dispatchEvent('input');assert.equal(await p.locator('#sIncome').inputValue(),'123,456');await p.locator('#sIncome').fill('46000');await p.locator('#saveSettingsBtn').click();await wait(60);assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('spfm_public_v1')).legacyExtra.keep),true,'unknown data lost');
await tab('quick');assert(await vis('#qCalendarBtn'),'calendar picker missing');assert.equal(await p.locator('#qDate').count(),1,'duplicate date field');assert.equal(await p.locator('.clean-date-row .clean-cal-btn').count(),1,'duplicate calendar button');await p.locator('#qAmt').fill('2345');await p.locator('#qNote').fill('ใหม่');let before=await p.evaluate(()=>S.tx.length);await p.locator('#saveTxBtn').click();await wait(100);assert.equal(await p.evaluate(()=>S.tx.length),before+1);assert(await vis('#dash'));
await tab('hist');const m1=await p.locator('#hcTitle').innerText();await p.locator('#hcPrev').click();await wait(30);const m2=await p.locator('#hcTitle').innerText();assert.notEqual(m1,m2);await p.locator('#hcNext').click();await wait(30);assert.equal(await p.locator('#hcTitle').innerText(),m1);
await tab('position');assert.equal(await p.locator('#assetsFoldBtn').count(),1);assert.equal(await p.locator('#debtsFoldBtn').count(),1);const na=await p.evaluate(()=>S.assets.length),nd=await p.evaluate(()=>S.debts.length);await p.locator('#addAssetBtn').click();await p.locator('[data-pos-type="asset"][data-pos-i="3"]').click();assert(await vis('#peHasDebt'));await p.locator('#peName').fill('บ้านทดสอบ');await p.locator('#peValue').fill('3000000');await p.locator('#peHasDebt').check();await p.locator('#peBalance').fill('2000000');await p.locator('#pePayment').fill('18000');await p.locator('#peSave').click();await wait(120);assert.equal(await p.evaluate(()=>S.assets.length),na+1);assert.equal(await p.evaluate(()=>S.debts.length),nd+1);
await tab('future');assert((await p.locator('#goalList').innerText()).includes('รถใหม่'));await p.locator('#wfType').selectOption('prepay');assert(await vis('#wfPrepay'));
await tab('dash');assert(await vis('#mpfInstallCard'));const man=await ctx.request.get(new URL('manifest.webmanifest',BASE).toString());assert(man.ok());const sw=await ctx.request.get(new URL('service-worker.js',BASE).toString());assert(sw.ok());if(errors.length)throw new Error(errors.join('\n'));await browser.close();console.log('CLEAN MAIN-PARITY QA PASS');