import { chromium } from 'playwright';
import assert from 'node:assert/strict';

const BASE=process.env.QA_BASE_URL||'http://127.0.0.1:4173/';
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:412,height:915},isMobile:true,hasTouch:true,acceptDownloads:true});
const page=await context.newPage();
const jsErrors=[];
page.on('pageerror',e=>jsErrors.push(`pageerror: ${e.message}`));
page.on('console',m=>{if(m.type()==='error')jsErrors.push(`console: ${m.text()}`)});
page.on('dialog',d=>d.accept().catch(()=>{}));
const wait=ms=>page.waitForTimeout(ms);
const count=sel=>page.locator(sel).count();
async function visible(sel){return page.locator(sel).first().isVisible().catch(()=>false)}
async function clean(root='body'){const t=await page.locator(root).innerText();assert(!/\bNaN\b|\bInfinity\b|\bundefined\b|null\s*บาท/i.test(t),`invalid calculated text in ${root}`)}
async function tab(id){const b=page.locator(`.tabs button[data-p="${id}"]`);assert.equal(await b.count(),1,`missing tab ${id}`);await b.click();await wait(180);assert.equal(await visible(`#${id}`),true,`tab ${id} did not open`)}
async function closeModal(sel){const m=page.locator(sel).last();if(!(await m.count())||!(await m.isVisible().catch(()=>false)))return;const c=m.locator('button').filter({hasText:/ปิด|ยกเลิก|Cancel|ไว้ก่อน/i}).first();if(await c.count())await c.click();else await page.keyboard.press('Escape');await wait(120)}

await page.goto(BASE,{waitUntil:'domcontentloaded',timeout:120000});
await page.evaluate(async()=>{if('serviceWorker' in navigator) await navigator.serviceWorker.ready});
await page.reload({waitUntil:'networkidle',timeout:120000});await wait(900);
assert(await count('#mpfBootTheme'),'production service-worker shell missing');
if(await visible('#mpfFirstStart')){const go=page.locator('#mpfFirstStart button').filter({hasText:/ไปที่ตั้งค่า/}).first();assert(await go.count(),'first-start action missing');await go.click();await wait(150);assert.equal(await visible('#settings'),true,'first-start -> settings failed');await closeModal('#settings')}

await page.evaluate(()=>{const S={profile:{name:'QA',income:46000,saving:8000,emerTarget:6,initialized:true},plans:[{id:'p1',name:'ค่าเช่า',amount:9000},{id:'p2',name:'เดินทาง',amount:3000}],annual:[{id:'a1',name:'ประกัน',amount:12000}],assets:[{id:'as1',name:'เงินฝาก',kind:'พร้อมใช้',value:30000},{id:'as2',name:'เงินฉุกเฉิน',kind:'Emergency',value:30000}],debts:[{id:'d1',name:'หนี้บ้าน',balance:400000,payment:5000,rate:4.5}],goals:[{id:'g1',name:'รถใหม่',target:900000,current:150000},{id:'g2',name:'บ้าน',target:5000000,current:250000}],tx:[{id:'t1',type:'expense',amount:1200,cat:'อาหาร',date:'2026-09-06',note:'ทดสอบ'}]};localStorage.setItem('spfm_public_v1',JSON.stringify(S));localStorage.setItem('mpf_first_start_notice_v1','1');localStorage.removeItem('spfm_ui_settings_fold_v1')});
await page.reload({waitUntil:'networkidle',timeout:120000});await wait(1000);assert.equal(await visible('#mpfFirstStart'),false,'first-start returned after initialized state');

assert.equal(await count('.tabs button'),5,'five bottom tabs expected');for(const id of ['dash','quick','hist','position','future']){await tab(id);await clean(`#${id}`)}
await tab('dash');const calc=await page.evaluate(()=>({p:plan(),a:ac(),goals:S.goals.length}));assert.equal(calc.p.inc,46000,'plan income formula wrong');assert.equal(calc.p.ex,12000,'monthly expense sum wrong');assert.equal(calc.p.an,1000,'annual monthly allocation wrong');assert.equal(calc.p.remain,33000,'planned remainder wrong');assert.equal(calc.a.total,60000,'asset total wrong');assert.equal(calc.a.debt,400000,'debt total wrong');assert.equal(calc.a.net,-340000,'net worth wrong');assert.equal(calc.goals,2,'seeded goals missing');await clean('#dash');

await page.locator('header button').filter({hasText:'วิธีใช้'}).click();await wait(120);assert.equal(await visible('#guide'),true,'guide popup failed');await closeModal('#guide');

await page.locator('header button').last().click();await wait(250);assert.equal(await visible('#settings'),true,'settings popup failed');const sheet=page.locator('#settings .sheet');assert(await sheet.count(),'settings sheet missing');assert((await sheet.evaluate(el=>el.scrollTop))<=2,'settings should open at top');const sticky=await page.locator('#settings .sheet>.itemtop:first-child').evaluate(el=>getComputedStyle(el).position);assert.equal(sticky,'sticky','settings title should be sticky');await page.locator('#sIncome').fill('123456');await page.locator('#sIncome').dispatchEvent('input');assert((await page.locator('#sIncome').inputValue()).includes(','),'settings comma formatting failed');const folds=page.locator('#settings .sf-toggle');assert((await folds.count())>=2,'monthly/annual fold controls missing');for(let i=0;i<2;i++){await folds.nth(i).click();await wait(50);await folds.nth(i).click()}const planBefore=await page.locator('#plans .item').count();const planCard=page.locator('#plans').locator('xpath=ancestor::*[contains(@class,"card")][1]');await planCard.locator('button').filter({hasText:/เพิ่ม/}).first().click();await wait(100);assert((await page.locator('#plans .item').count())===planBefore+1,'add monthly plan failed');const annualBefore=await page.locator('#annuals .item').count();const annualCard=page.locator('#annuals').locator('xpath=ancestor::*[contains(@class,"card")][1]');await annualCard.locator('button').filter({hasText:/เพิ่ม/}).first().click();await wait(100);assert((await page.locator('#annuals .item').count())===annualBefore+1,'add annual plan failed');const backup=page.locator('#settings button').filter({hasText:/สำรอง JSON|สำรองข้อมูลลงเครื่อง|Backup/i}).first();assert(await backup.count(),'backup missing');const downloadPromise=page.waitForEvent('download',{timeout:5000}).catch(()=>null);await backup.click();assert(await downloadPromise,'backup did not start a download');const restore=page.locator('#settings button').filter({hasText:/นำเข้า JSON|กู้คืนข้อมูลจากไฟล์|Restore/i}).first();assert(await restore.count(),'restore control missing');const saveSettings=page.locator('#settings button').filter({hasText:/^\s*บันทึก(?:การตั้งค่า)?\s*$/}).first();assert(await saveSettings.count(),'settings save missing');await saveSettings.click();await wait(180);assert.equal(await visible('#settings'),false,'settings save did not close');

await tab('quick');const beforeTx=await page.evaluate(()=>S.tx.length);await page.locator('#qAmt').fill('2345');await page.locator('#qAmt').dispatchEvent('input');assert((await page.locator('#qAmt').inputValue()).includes(','),'quick amount comma failed');await page.locator('#qDate').fill('06/09/2026');await page.locator('#qDate').dispatchEvent('input');if(await page.locator('#qCat option').count()>1)await page.locator('#qCat').selectOption({index:1});const qsave=page.locator('#quick button').filter({hasText:/^\s*บันทึก\s*$/}).first();assert(await qsave.count(),'quick save missing');await qsave.click();await wait(220);const afterTx=await page.evaluate(()=>S.tx.length);assert(afterTx===beforeTx+1,'quick transaction save failed');

await tab('hist');assert(await count('#histCalTabs'),'history view tabs missing');assert(await count('#histCalCard'),'history calendar missing');const calTab=page.locator('#histCalTabs button').filter({hasText:'ปฏิทิน'});await calTab.click();await wait(100);assert.equal(await visible('#histCalCard'),true,'calendar view failed');const monthTitleBefore=await page.locator('#histCalCard .hc-head b').innerText();await page.locator('#hcPrev').click();await wait(100);const monthTitleAfter=await page.locator('#histCalCard .hc-head b').innerText();assert.notEqual(monthTitleBefore,monthTitleAfter,'calendar previous month failed');await page.locator('#hcNext').click();const days=page.locator('#histCalCard .hc-day');if(await days.count())await days.first().click();const analysisTab=page.locator('#histCalTabs button').filter({hasText:'วิเคราะห์'});await analysisTab.click();await wait(100);assert.equal(await visible('#histAnalysisWrap'),true,'history analysis view failed');if(await page.locator('#hType').isVisible().catch(()=>false)){await page.locator('#hType').selectOption('expense');await page.locator('#hType').selectOption('all')}await clean('#hist');

await tab('position');assert(await count('#peTop'),'current Position toolbar missing');const aBefore=await page.evaluate(()=>S.assets.length);const addAsset=page.locator('#peTop button').filter({hasText:/เพิ่มเงิน \/ ทรัพย์สิน/}).first();assert(await addAsset.count(),'current asset add button missing');await addAsset.click();await wait(100);assert.equal(await visible('#peModal'),true,'asset chooser popup failed');await page.locator('#peModal .pe-choice').first().click();await wait(80);await page.locator('#peName').fill('บัญชี QA');await page.locator('#peValue').fill('50000');await page.locator('#peValue').dispatchEvent('input');const saveAsset=page.locator('#peModal button').filter({hasText:/บันทึก/}).first();await saveAsset.click();await wait(150);assert((await page.evaluate(()=>S.assets.length))===aBefore+1,'asset save failed');
const dBefore=await page.evaluate(()=>S.debts.length);const addDebt=page.locator('#peTop button').filter({hasText:/เพิ่มหนี้/}).first();assert(await addDebt.count(),'current debt add button missing');await addDebt.click();await wait(100);assert.equal(await visible('#peModal'),true,'debt chooser popup failed');await page.locator('#peModal .pe-choice').first().click();await wait(80);await page.locator('#peName').fill('หนี้ QA');await page.locator('#peBalance').fill('100000');await page.locator('#pePayment').fill('5000');await page.locator('#peModal button').filter({hasText:/บันทึก/}).first().click();await wait(150);assert((await page.evaluate(()=>S.debts.length))===dBefore+1,'debt save failed');await clean('#position');

await tab('future');await wait(220);assert(await count('#mpfGoalsEditor'),'goal editor missing');const goalsText=await page.locator('#mpfGoalsEditor').innerText();assert(goalsText.includes('รถใหม่')&&goalsText.includes('บ้าน'),'shared goals not shown');const legacy=page.locator('#fSave').locator('xpath=ancestor::*[contains(@class,"card")][1]');if(await legacy.count())assert.equal(await legacy.isVisible(),false,'duplicate Future summary still visible');const wfGoal=page.locator('#wfGoal');assert(await wfGoal.count(),'What-if goal selector missing');await wfGoal.selectOption('g2');await wait(120);if(await count('#wfPrice'))assert((await page.locator('#wfPrice').inputValue()).includes(','),'What-if target comma missing');if(await count('#wfPrice')){await page.locator('#wfPrice').fill('1500000');await page.locator('#wfPrice').dispatchEvent('input')}if(await count('#wfCash')){await page.locator('#wfCash').fill('300000');await page.locator('#wfCash').dispatchEvent('input')}if(await count('#whatIfCard'))await clean('#whatIfCard');const addGoal=page.locator('#mpfGoalsEditor button').filter({hasText:/เพิ่ม/}).first();await addGoal.click();await wait(100);assert.equal(await visible('#mpfGoalModal'),true,'goal popup failed');await page.locator('#mpfGoalName').fill('เที่ยวญี่ปุ่น');await page.locator('#mpfGoalTarget').fill('120000');await page.locator('#mpfGoalTarget').dispatchEvent('input');await page.locator('#mpfGoalCurrent').fill('20000');await page.locator('#mpfGoalCurrent').dispatchEvent('input');assert((await page.locator('#mpfGoalTarget').inputValue()).includes(','),'goal popup comma failed');await page.locator('#mpfGoalModal button').filter({hasText:/บันทึก/}).click();await wait(200);await tab('dash');assert((await page.locator('#dash').innerText()).includes('เที่ยวญี่ปุ่น'),'new goal did not sync to dashboard');

const manifest=await page.request.get(new URL('manifest.webmanifest',BASE).href);assert(manifest.ok(),'manifest unavailable');const manifestJson=await manifest.json();assert(manifestJson.name||manifestJson.short_name,'manifest name missing');const sw=await page.request.get(new URL('service-worker.js',BASE).href);assert(sw.ok(),'service worker unavailable');const swText=await sw.text();assert(!swText.includes('dashboard-goal-sync-v1.js'),'SW references deleted dashboard script');const reg=await page.evaluate(async()=>!!(await navigator.serviceWorker.getRegistration()));assert(reg,'service worker registration missing');
for(const sel of ['header button:visible','.tabs button:visible','#dash button:visible','#quick button:visible','#hist button:visible','#position button:visible','#future button:visible']){const bs=page.locator(sel);for(let i=0;i<await bs.count();i++){const b=bs.nth(i);const label=((await b.innerText().catch(()=>''))||await b.getAttribute('aria-label')||await b.getAttribute('title')||'').trim();assert(label,`unlabeled visible button: ${sel} #${i}`)}}await clean('body');
await browser.close();if(jsErrors.length){console.error(jsErrors.join('\n'));process.exit(1)}console.log('QA PASS v2: production shell, first-start, navigation, formulas, settings, backup, quick entry, history, current Position flows, goals, What-if, popups and PWA essentials.');
