import { chromium } from 'playwright';
import assert from 'node:assert/strict';
const BASE=process.env.QA_BASE_URL||'http://127.0.0.1:4173/';
const browser=await chromium.launch({headless:true});
const ctx=await browser.newContext({viewport:{width:412,height:915},isMobile:true,hasTouch:true,acceptDownloads:true});
const p=await ctx.newPage(), errs=[];
p.on('pageerror',e=>errs.push('pageerror: '+e.message));
p.on('console',m=>{if(m.type()==='error')errs.push('console: '+m.text())});
p.on('dialog',d=>d.accept(d.type()==='prompt'?'QA รายการ':'').catch(()=>{}));
const wait=n=>p.waitForTimeout(n), vis=async s=>p.locator(s).first().isVisible().catch(()=>false);
async function tab(id){const b=p.locator(`.tabs button[data-p="${id}"]`);assert.equal(await b.count(),1,`tab ${id}`);await b.click();await wait(120);assert(await vis(`#${id}`),`${id} not visible`)}
async function clean(s='body'){const t=await p.locator(s).innerText();assert(!/\bNaN\b|\bInfinity\b|\bundefined\b|null\s*บาท/i.test(t),`bad calculated text ${s}`)}
async function cards(id){await tab(id);const cs=p.locator(`#${id} .card:visible, #${id} .dv2-sec:visible, #${id} #pvCard:visible, #${id} #whatIfCard:visible, #${id} #mpfGoalsEditor:visible`);assert((await cs.count())>0,`${id} no visible content cards`);for(let i=0;i<await cs.count();i++){const c=cs.nth(i),box=await c.boundingBox();assert(box&&box.width>20&&box.height>20,`${id} card ${i} bad size`)}await clean(`#${id}`)}

await p.goto(BASE,{waitUntil:'domcontentloaded'});await p.evaluate(async()=>{if(navigator.serviceWorker)await navigator.serviceWorker.ready});await p.reload({waitUntil:'networkidle'});await wait(700);
assert(await p.locator('#mpfBootTheme').count(),'SW shell missing');
await p.evaluate(()=>{localStorage.removeItem('spfm_public_v1');localStorage.removeItem('mpf_first_start_notice_v1')});await p.reload({waitUntil:'networkidle'});await wait(500);assert(await vis('#mpfFirstStart'),'first-start popup missing');assert((await p.locator('#mpfFirstStart').innerText()).includes('เริ่มต้นที่ “ตั้งค่า”'));await p.locator('#mpfFirstStart button').filter({hasText:/ไปที่ตั้งค่า/}).click();assert(await vis('#settings'));await p.locator('#settings button').filter({hasText:/ปิด/}).first().click();
await p.evaluate(()=>{const x={profile:{name:'QA',income:46000,saving:8000,emerTarget:6,initialized:true},plans:[{id:'p1',name:'ค่าเช่า',amount:9000},{id:'p2',name:'เดินทาง',amount:3000}],annual:[{id:'a1',name:'ประกัน',amount:12000}],assets:[{id:'as1',name:'เงินฝาก',kind:'พร้อมใช้',value:30000},{id:'as2',name:'เงินฉุกเฉิน',kind:'Emergency',value:30000}],debts:[{id:'d1',name:'หนี้บ้าน',balance:400000,payment:5000,rate:4.5}],goals:[{id:'g1',name:'รถใหม่',target:900000,current:150000},{id:'g2',name:'บ้าน',target:5000000,current:250000}],tx:[{id:'t1',type:'expense',amount:1200,cat:'อาหาร',date:'2026-09-06',note:'QA'}]};localStorage.setItem('spfm_public_v1',JSON.stringify(x));localStorage.setItem('mpf_first_start_notice_v1','1')});await p.reload({waitUntil:'networkidle'});await wait(700);
for(const id of ['dash','quick','hist','position','future'])await cards(id);
await tab('dash');const c=await p.evaluate(()=>({p:plan(),a:ac()}));assert.deepEqual(c.p,{inc:46000,ex:12000,an:1000,remain:33000});assert.equal(c.a.total,60000);assert.equal(c.a.debt,400000);assert.equal(c.a.net,-340000);const dashTxt=await p.locator('#dash').innerText();for(const x of ['46,000','12,000','1,000','33,000'])assert(dashTxt.replace(/฿/g,'').includes(x),`dashboard missing ${x}`);
await p.locator('header button').filter({hasText:'วิธีใช้'}).click();assert(await vis('#guide'));await p.locator('#guide button').filter({hasText:/ปิด/}).click();
await p.locator('header button').last().click();await wait(150);assert(await vis('#settings'));assert((await p.locator('#settings').innerText()).includes('ข้อมูลพื้นฐาน'));assert((await p.locator('#settings').innerText()).includes('สำรองและกู้คืนข้อมูล'));assert.equal(await p.locator('#settings .sheet>.itemtop:first-child').evaluate(e=>getComputedStyle(e).position),'sticky');await p.locator('#sIncome').fill('123456');await p.locator('#sIncome').dispatchEvent('input');assert.equal(await p.locator('#sIncome').inputValue(),'123,456');const folds=p.locator('#settings .sf-toggle');assert((await folds.count())>=2);for(let i=0;i<2;i++){await folds.nth(i).click();await folds.nth(i).click()}const dp=p.waitForEvent('download',{timeout:4000}).catch(()=>null);await p.locator('#settings button').filter({hasText:/สำรองข้อมูลลงเครื่อง/}).click();assert(await dp,'backup download missing');assert(await p.locator('#restore').count(),'restore input missing');await p.locator('#settings button').filter({hasText:/บันทึกการตั้งค่า/}).click();assert(!(await vis('#settings')));
await tab('quick');assert(await vis('#quick .moji-icon-strip'),'category icon strip missing');assert((await p.locator('#quick .moji-icon-chip').count())>=5,'too few category icons');await p.locator('#quick .qe-calc-btn').click();assert(await vis('.qe-calc-modal'));await p.locator('.qe-calc-close').click();const tb=await p.evaluate(()=>S.tx.length);await p.locator('#qAmt').fill('2345');await p.locator('#qAmt').dispatchEvent('input');assert.equal(await p.locator('#qAmt').inputValue(),'2,345');await p.locator('#qDate').fill('06/09/2026');await p.locator('#qDate').dispatchEvent('input');if(await p.locator('#qCat option').count()>1)await p.locator('#qCat').selectOption({index:1});await p.locator('#quick button').filter({hasText:/^\s*บันทึก\s*$/}).first().click();await wait(120);assert.equal(await p.evaluate(()=>S.tx.length),tb+1);
await tab('hist');assert(await p.locator('#histCalTabs').count());await p.locator('#histCalTabs button').filter({hasText:'ปฏิทิน'}).click();assert(await vis('#histCalCard'));const m1=await p.locator('#histCalCard .hc-head b').innerText();await p.locator('#hcPrev').click();const m2=await p.locator('#histCalCard .hc-head b').innerText();assert.notEqual(m1,m2);await p.locator('#hcNext').click();await p.locator('#histCalTabs button').filter({hasText:'วิเคราะห์'}).click();assert(await vis('#histAnalysisWrap'));const graphCount=await p.locator('#hist .hist-donut, #hist .bar-fill, #hist svg, #hist canvas').count();assert(graphCount>0,'history graph missing');await clean('#hist');
await tab('position');assert(await vis('#pvCard'));assert((await p.locator('#pvCard .pv-bar').count())>=3,'position graph bars missing');for(const b of await p.locator('#pvCard .pv-bar').all()){const box=await b.boundingBox();assert(box&&box.height>0,'zero-height position graph')}let n=await p.evaluate(()=>S.assets.length);await p.locator('#pvCard .pv-actions button').filter({hasText:/เพิ่มเงิน \/ ทรัพย์สิน/}).click();assert(await vis('#peModal'));await p.locator('#peModal .pe-choice').first().click();await p.locator('#peName').fill('บัญชี QA');await p.locator('#peValue').fill('50000');await p.locator('#peModal button').filter({hasText:/บันทึก/}).click();assert.equal(await p.evaluate(()=>S.assets.length),n+1);n=await p.evaluate(()=>S.debts.length);await p.locator('#pvCard .pv-actions button').filter({hasText:/เพิ่มหนี้/}).click();assert(await vis('#peModal'));await p.locator('#peModal .pe-choice').first().click();await p.locator('#peName').fill('หนี้ QA');await p.locator('#peBalance').fill('100000');await p.locator('#pePayment').fill('5000');await p.locator('#peModal button').filter({hasText:/บันทึก/}).click();assert.equal(await p.evaluate(()=>S.debts.length),n+1);await clean('#position');
await tab('future');assert(await p.locator('#mpfGoalsEditor').count());const gt=await p.locator('#mpfGoalsEditor').innerText();assert(gt.includes('รถใหม่')&&gt.includes('บ้าน'));const gs=p.locator('#wfGoal');assert(await gs.count());await gs.selectOption('g2');assert((await p.locator('#wfPrice').inputValue()).includes(','));await p.locator('#wfPrice').fill('1500000');await p.locator('#wfPrice').dispatchEvent('input');await p.locator('#wfCash').fill('300000');await p.locator('#wfCash').dispatchEvent('input');await clean('#whatIfCard');await p.locator('#mpfGoalsEditor button').filter({hasText:/เพิ่ม/}).first().click();assert(await vis('#mpfGoalModal'));await p.locator('#mpfGoalName').fill('เที่ยวญี่ปุ่น');await p.locator('#mpfGoalTarget').fill('120000');await p.locator('#mpfGoalTarget').dispatchEvent('input');assert.equal(await p.locator('#mpfGoalTarget').inputValue(),'120,000');await p.locator('#mpfGoalCurrent').fill('20000');await p.locator('#mpfGoalModal button').filter({hasText:/บันทึก/}).click();await tab('dash');assert((await p.locator('#dash').innerText()).includes('เที่ยวญี่ปุ่น'));
assert(await vis('#mpfInstallCard'),'install card missing');await p.locator('#mpfInstallBtn').click();assert(await vis('#mpfInstallHelp'),'install help missing');await p.evaluate(()=>{window.__qaPromptCalled=false;const e=new Event('beforeinstallprompt');Object.defineProperty(e,'prompt',{value:()=>{window.__qaPromptCalled=true}});Object.defineProperty(e,'userChoice',{value:Promise.resolve({outcome:'accepted'})});window.dispatchEvent(e)});await p.locator('#mpfInstallBtn').click();await wait(80);assert(await p.evaluate(()=>window.__qaPromptCalled),'native install prompt path not called');const man=await ctx.request.get(new URL('manifest.webmanifest',BASE).toString());assert(man.ok());const manifest=await man.json();assert(manifest.name&&manifest.icons?.length>=2,'manifest incomplete');const sw=await ctx.request.get(new URL('service-worker.js',BASE).toString());assert(sw.ok());const swt=await sw.text();assert(swt.includes('moji-elegant-ui-v1.js'));assert(!swt.includes('dashboard-goal-sync-v1.js'));assert(await p.evaluate(async()=>!!(await navigator.serviceWorker.getRegistration())),'service worker not registered');
const bs=p.locator('button:visible');for(let i=0;i<await bs.count();i++){const b=bs.nth(i),lab=((await b.innerText().catch(()=>''))||await b.getAttribute('aria-label')||await b.getAttribute('title')||'').trim();assert(lab,`unlabeled button ${i}`)}assert(await p.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+2),'horizontal overflow');await clean();await browser.close();if(errs.length){console.error(errs.join('\n'));process.exit(1)}console.log('QA PASS v4');
