import { chromium } from 'playwright';
import assert from 'node:assert/strict';
const BASE=process.env.QA_BASE_URL||'http://127.0.0.1:4173/';
const browser=await chromium.launch({headless:true});
const ctx=await browser.newContext({viewport:{width:412,height:915},isMobile:true,hasTouch:true,acceptDownloads:true});
const p=await ctx.newPage(), errs=[];
p.on('pageerror',e=>errs.push('pageerror: '+e.message));
p.on('console',m=>{if(m.type()==='error')errs.push('console: '+m.text())});
p.on('dialog',d=>d.accept(d.type()==='prompt'?'QA รายการ':'').catch(()=>{}));
const wait=n=>p.waitForTimeout(n);
const vis=async s=>p.locator(s).first().isVisible().catch(()=>false);
async function tab(id){const b=p.locator(`.tabs button[data-p="${id}"]`);assert.equal(await b.count(),1,`missing tab ${id}`);await b.click();await wait(100);assert(await vis(`#${id}`),`${id} not visible`)}
async function clean(s='body'){const t=await p.locator(s).innerText();assert(!/\bNaN\b|\bInfinity\b|\bundefined\b|null\s*บาท/i.test(t),`bad calculated text ${s}`)}
async function pageCheck(id){await tab(id);const t=(await p.locator(`#${id}`).innerText()).trim();assert(t.length>15,`${id} empty`);await clean(`#${id}`);assert(await p.evaluate(id=>{const e=document.getElementById(id),r=e.getBoundingClientRect();return r.width>100&&r.height>50},id),`${id} bad layout`)}

await p.goto(BASE,{waitUntil:'domcontentloaded'});await p.evaluate(async()=>{if(navigator.serviceWorker)await navigator.serviceWorker.ready});await p.reload({waitUntil:'networkidle'});await wait(600);assert(await p.locator('#mpfBootTheme').count(),'service-worker shell missing');

// Fresh-install first-start popup.
await p.evaluate(()=>{localStorage.removeItem('spfm_public_v1');localStorage.removeItem('mpf_first_start_notice_v1')});await p.reload({waitUntil:'networkidle'});await wait(500);assert(await vis('#mpfFirstStart'),'first-start popup missing');assert((await p.locator('#mpfFirstStart').innerText()).includes('เริ่มต้นที่ “ตั้งค่า”'));await p.locator('#mpfFirstStart button').filter({hasText:/ไปที่ตั้งค่า/}).click();assert(await vis('#settings'),'settings did not open from first-start');await p.locator('#settings button').filter({hasText:/ปิด/}).first().click();

// Seed deterministic business data.
await p.evaluate(()=>{const x={profile:{name:'QA',income:46000,saving:8000,emerTarget:6,initialized:true},plans:[{id:'p1',name:'ค่าเช่า',amount:9000},{id:'p2',name:'เดินทาง',amount:3000}],annual:[{id:'a1',name:'ประกัน',amount:12000}],assets:[{id:'as1',name:'เงินฝาก',kind:'พร้อมใช้',value:30000},{id:'as2',name:'เงินฉุกเฉิน',kind:'Emergency',value:30000}],debts:[{id:'d1',name:'หนี้บ้าน',balance:400000,payment:5000,rate:4.5}],goals:[{id:'g1',name:'รถใหม่',target:900000,current:150000},{id:'g2',name:'บ้าน',target:5000000,current:250000}],tx:[{id:'t1',type:'expense',amount:1200,cat:'อาหาร',date:'2026-09-06',note:'QA'}]};localStorage.setItem('spfm_public_v1',JSON.stringify(x));localStorage.setItem('mpf_first_start_notice_v1','1')});await p.reload({waitUntil:'networkidle'});await wait(600);

// Every primary menu renders and contains valid calculated text.
for(const id of ['dash','quick','hist','position','future'])await pageCheck(id);

// Core financial calculation engine.
await tab('dash');const c=await p.evaluate(()=>({p:plan(),a:ac()}));assert.deepEqual(c.p,{inc:46000,ex:12000,an:1000,remain:33000});assert.equal(c.a.total,60000);assert.equal(c.a.debt,400000);assert.equal(c.a.net,-340000);const dt=(await p.locator('#dash').innerText()).replace(/฿/g,'');for(const x of ['46,000','12,000','1,000','33,000'])assert(dt.includes(x),`dashboard metric missing ${x}`);

// Guide popup.
await p.locator('header button').filter({hasText:'วิธีใช้'}).click();assert(await vis('#guide'),'guide popup missing');await p.locator('#guide button').filter({hasText:/ปิด/}).click();

// Agreed Settings UI and interactions.
await p.locator('header button').last().click();await wait(120);assert(await vis('#settings'));const st=await p.locator('#settings').innerText();for(const x of ['ตั้งค่าการเงิน','ข้อมูลพื้นฐาน','ค่าใช้จ่ายประจำ / งบต่อเดือน','ค่าใช้จ่ายรายปี','สำรองและกู้คืนข้อมูล','บันทึกการตั้งค่า'])assert(st.includes(x),`settings missing ${x}`);assert.equal(await p.locator('#settings .sheet>.itemtop:first-child').evaluate(e=>getComputedStyle(e).position),'sticky');await p.locator('#sIncome').fill('123456');await p.locator('#sIncome').dispatchEvent('input');assert.equal(await p.locator('#sIncome').inputValue(),'123,456');const folds=p.locator('#settings .sf-toggle');assert((await folds.count())>=2,'settings fold buttons missing');for(let i=0;i<2;i++){await folds.nth(i).click();await folds.nth(i).click()}const dp=p.waitForEvent('download',{timeout:4000}).catch(()=>null);await p.locator('#settings button').filter({hasText:/สำรองข้อมูลลงเครื่อง/}).click();assert(await dp,'backup download missing');assert(await p.locator('#restore').count(),'restore input missing');await p.locator('#settings button').filter({hasText:/บันทึกการตั้งค่า/}).click();assert(!(await vis('#settings')),'settings did not close after save');

// Quick entry icons, calculator popup, numeric formatting and save.
await tab('quick');assert(await vis('#quick .moji-icon-strip'),'category icon strip missing');assert((await p.locator('#quick .moji-icon-chip').count())>=5,'category icon count too low');await p.locator('#quick .qe-calc-btn').click();assert(await vis('.qe-calc-modal'),'calculator popup missing');await p.locator('.qe-calc-close').click();const tb=await p.evaluate(()=>S.tx.length);await p.locator('#qAmt').fill('2345');await p.locator('#qAmt').dispatchEvent('input');assert.equal(await p.locator('#qAmt').inputValue(),'2,345');await p.locator('#qDate').fill('06/09/2026');await p.locator('#qDate').dispatchEvent('input');if(await p.locator('#qCat option').count()>1)await p.locator('#qCat').selectOption({index:1});await p.locator('#quick button').filter({hasText:/^\s*บันทึก\s*$/}).first().click();await wait(120);assert.equal(await p.evaluate(()=>S.tx.length),tb+1,'transaction save failed');

// History tabs, calendar, analysis and graph rendering.
await tab('hist');assert(await p.locator('#histCalTabs').count(),'history tabs missing');await p.locator('#histCalTabs button').filter({hasText:'ปฏิทิน'}).click();assert(await vis('#histCalCard'),'calendar card missing');const m1=await p.locator('#histCalCard .hc-head b').innerText();await p.locator('#hcPrev').click();const m2=await p.locator('#histCalCard .hc-head b').innerText();assert.notEqual(m1,m2,'calendar previous month failed');await p.locator('#hcNext').click();await p.locator('#histCalTabs button').filter({hasText:'วิเคราะห์'}).click();assert(await vis('#histAnalysisWrap'),'history analysis missing');assert((await p.locator('#hist .hist-donut, #hist .bar-fill, #hist svg, #hist canvas').count())>0,'history graph missing');await clean('#hist');

// Position graph and asset/debt popups.
await tab('position');assert(await vis('#pvCard'),'position visual card missing');assert((await p.locator('#pvCard .pv-bar').count())>=3,'position graph missing');for(const b of await p.locator('#pvCard .pv-bar').all()){const box=await b.boundingBox();assert(box&&box.height>0,'position graph zero height')}let n=await p.evaluate(()=>S.assets.length);await p.locator('#pvCard .pv-actions button').filter({hasText:/เพิ่มเงิน \/ ทรัพย์สิน/}).click();assert(await vis('#peModal'),'asset popup missing');await p.locator('#peModal .pe-choice').first().click();await p.locator('#peName').fill('บัญชี QA');await p.locator('#peValue').fill('50000');await p.locator('#peModal button').filter({hasText:/บันทึก/}).click();assert.equal(await p.evaluate(()=>S.assets.length),n+1,'asset save failed');n=await p.evaluate(()=>S.debts.length);await p.locator('#pvCard .pv-actions button').filter({hasText:/เพิ่มหนี้/}).click();assert(await vis('#peModal'),'debt popup missing');await p.locator('#peModal .pe-choice').first().click();await p.locator('#peName').fill('หนี้ QA');await p.locator('#peBalance').fill('100000');await p.locator('#pePayment').fill('5000');await p.locator('#peModal button').filter({hasText:/บันทึก/}).click();assert.equal(await p.evaluate(()=>S.debts.length),n+1,'debt save failed');await clean('#position');

// Future goals, What-if calculation input, goal popup and dashboard sync.
await tab('future');assert(await p.locator('#mpfGoalsEditor').count(),'goal editor missing');const gt=await p.locator('#mpfGoalsEditor').innerText();assert(gt.includes('รถใหม่')&&gt.includes('บ้าน'),'existing goals missing');const gs=p.locator('#wfGoal');assert(await gs.count(),'What-if goal selector missing');await gs.selectOption('g2');assert((await p.locator('#wfPrice').inputValue()).includes(','),'What-if target not formatted');await p.locator('#wfPrice').fill('1500000');await p.locator('#wfPrice').dispatchEvent('input');await p.locator('#wfCash').fill('300000');await p.locator('#wfCash').dispatchEvent('input');await clean('#whatIfCard');await p.locator('#mpfGoalsEditor button').filter({hasText:/เพิ่ม/}).first().click();assert(await vis('#mpfGoalModal'),'goal popup missing');await p.locator('#mpfGoalName').fill('เที่ยวญี่ปุ่น');await p.locator('#mpfGoalTarget').fill('120000');await p.locator('#mpfGoalTarget').dispatchEvent('input');assert.equal(await p.locator('#mpfGoalTarget').inputValue(),'120,000');await p.locator('#mpfGoalCurrent').fill('20000');await p.locator('#mpfGoalModal button').filter({hasText:/บันทึก/}).click();await tab('dash');assert((await p.locator('#dash').innerText()).includes('เที่ยวญี่ปุ่น'),'goal did not sync to dashboard');

// Install card, fallback instructions, native prompt code path, manifest and service worker.
assert(await vis('#mpfInstallCard'),'install card missing');await p.locator('#mpfInstallBtn').click();assert(await vis('#mpfInstallHelp'),'install fallback help missing');await p.evaluate(()=>{window.__qaPromptCalled=false;const e=new Event('beforeinstallprompt');Object.defineProperty(e,'prompt',{value:()=>{window.__qaPromptCalled=true}});Object.defineProperty(e,'userChoice',{value:Promise.resolve({outcome:'accepted'})});window.dispatchEvent(e)});await p.locator('#mpfInstallBtn').click();await wait(80);assert(await p.evaluate(()=>window.__qaPromptCalled),'native install prompt path not called');const man=await ctx.request.get(new URL('manifest.webmanifest',BASE).toString());assert(man.ok());const manifest=await man.json();assert(manifest.name&&manifest.icons?.length>=2,'manifest incomplete');const sw=await ctx.request.get(new URL('service-worker.js',BASE).toString());assert(sw.ok());const swt=await sw.text();assert(swt.includes('moji-elegant-ui-v1.js'),'service worker missing category icon script');assert(!swt.includes('dashboard-goal-sync-v1.js'),'stale removed script still cached');assert(await p.evaluate(async()=>!!(await navigator.serviceWorker.getRegistration())),'service worker not registered');

// Final UI integrity.
const bs=p.locator('button:visible');for(let i=0;i<await bs.count();i++){const b=bs.nth(i),lab=((await b.innerText().catch(()=>''))||await b.getAttribute('aria-label')||await b.getAttribute('title')||'').trim();assert(lab,`unlabeled visible button ${i}`)}await clean();
await browser.close();if(errs.length){console.error(errs.join('\n'));process.exit(1)}console.log('QA PASS v5');
