import { chromium } from 'playwright';
import assert from 'node:assert/strict';
const BASE=process.env.QA_BASE_URL||'http://127.0.0.1:4173/';
const browser=await chromium.launch({headless:true});
const ctx=await browser.newContext({viewport:{width:412,height:915},isMobile:true,hasTouch:true,acceptDownloads:true});
const p=await ctx.newPage(), errs=[];p.on('pageerror',e=>errs.push(e.message));p.on('console',m=>{if(m.type()==='error')errs.push(m.text())});p.on('dialog',d=>d.accept().catch(()=>{}));
const wait=n=>p.waitForTimeout(n), vis=async s=>p.locator(s).first().isVisible().catch(()=>false);
async function tab(id){const b=p.locator(`.tabs button[data-p="${id}"]`);assert.equal(await b.count(),1);await b.click();await wait(120);assert(await vis(`#${id}`),`${id} not visible`)}
async function clean(s='body'){assert(!/\bNaN\b|\bInfinity\b|\bundefined\b|null\s*บาท/i.test(await p.locator(s).innerText()),`bad calculated text ${s}`)}
async function close(s){const m=p.locator(s).last();if(await m.isVisible().catch(()=>false)){const b=m.locator('button').filter({hasText:/ปิด|ยกเลิก|ไว้ก่อน/}).first();if(await b.count())await b.click();else await p.keyboard.press('Escape');await wait(80)}}

await p.goto(BASE,{waitUntil:'domcontentloaded'});await p.evaluate(async()=>{if(navigator.serviceWorker)await navigator.serviceWorker.ready});await p.reload({waitUntil:'networkidle'});await wait(700);assert(await p.locator('#mpfBootTheme').count(),'SW app shell missing');
if(await vis('#mpfFirstStart')){await p.locator('#mpfFirstStart button').filter({hasText:/ไปที่ตั้งค่า/}).click();assert(await vis('#settings'));await close('#settings')}
await p.evaluate(()=>{const x={profile:{name:'QA',income:46000,saving:8000,emerTarget:6,initialized:true},plans:[{id:'p1',name:'ค่าเช่า',amount:9000},{id:'p2',name:'เดินทาง',amount:3000}],annual:[{id:'a1',name:'ประกัน',amount:12000}],assets:[{id:'a1',name:'เงินฝาก',kind:'พร้อมใช้',value:30000},{id:'a2',name:'เงินฉุกเฉิน',kind:'Emergency',value:30000}],debts:[{id:'d1',name:'หนี้บ้าน',balance:400000,payment:5000,rate:4.5}],goals:[{id:'g1',name:'รถใหม่',target:900000,current:150000},{id:'g2',name:'บ้าน',target:5000000,current:250000}],tx:[{id:'t1',type:'expense',amount:1200,cat:'อาหาร',date:'2026-09-06',note:'QA'}]};localStorage.setItem('spfm_public_v1',JSON.stringify(x));localStorage.setItem('mpf_first_start_notice_v1','1')});await p.reload({waitUntil:'networkidle'});await wait(700);

// Navigation + formulas.
for(const id of ['dash','quick','hist','position','future']){await tab(id);await clean(`#${id}`)}await tab('dash');const c=await p.evaluate(()=>({p:plan(),a:ac()}));assert.deepEqual(c.p,{inc:46000,ex:12000,an:1000,remain:33000});assert.equal(c.a.total,60000);assert.equal(c.a.debt,400000);assert.equal(c.a.net,-340000);

// Guide.
await p.locator('header button').filter({hasText:'วิธีใช้'}).click();assert(await vis('#guide'));await close('#guide');

// Settings current mobile UI + comma + folds + add + backup + save.
await p.locator('header button').last().click();await wait(150);assert(await vis('#settings'));const sh=p.locator('#settings .sheet');assert((await sh.evaluate(e=>e.scrollTop))<=2);assert.equal(await p.locator('#settings .sheet>.itemtop:first-child').evaluate(e=>getComputedStyle(e).position),'sticky');await p.locator('#sIncome').fill('123456');await p.locator('#sIncome').dispatchEvent('input');assert.equal(await p.locator('#sIncome').inputValue(),'123,456');const folds=p.locator('#settings .sf-toggle');assert((await folds.count())>=2);for(let i=0;i<2;i++){await folds.nth(i).click();await folds.nth(i).click()}const pb=await p.locator('#plans .item').count();await p.locator('#plans').locator('xpath=ancestor::*[contains(@class,"card")][1]').locator('button').filter({hasText:/เพิ่ม/}).first().click();assert.equal(await p.locator('#plans .item').count(),pb+1);const ab=await p.locator('#annuals .item').count();await p.locator('#annuals').locator('xpath=ancestor::*[contains(@class,"card")][1]').locator('button').filter({hasText:/เพิ่ม/}).first().click();assert.equal(await p.locator('#annuals .item').count(),ab+1);const backup=p.locator('#settings button').filter({hasText:/สำรอง JSON|สำรองข้อมูลลงเครื่อง/}).first();const dp=p.waitForEvent('download',{timeout:4000}).catch(()=>null);await backup.click();assert(await dp,'backup download missing');assert(await p.locator('#restore').count(),'restore file input missing');await p.locator('#settings button').filter({hasText:/^\s*บันทึก(?:การตั้งค่า)?\s*$/}).click();assert(!(await vis('#settings')));

// Quick entry save + comma/date.
await tab('quick');const tb=await p.evaluate(()=>S.tx.length);await p.locator('#qAmt').fill('2345');await p.locator('#qAmt').dispatchEvent('input');assert.equal(await p.locator('#qAmt').inputValue(),'2,345');await p.locator('#qDate').fill('06/09/2026');await p.locator('#qDate').dispatchEvent('input');if(await p.locator('#qCat option').count()>1)await p.locator('#qCat').selectOption({index:1});await p.locator('#quick button').filter({hasText:/^\s*บันทึก\s*$/}).first().click();await wait(120);assert.equal(await p.evaluate(()=>S.tx.length),tb+1);

// Current History tabs/calendar/analysis.
await tab('hist');assert(await p.locator('#histCalTabs').count());await p.locator('#histCalTabs button').filter({hasText:'ปฏิทิน'}).click();assert(await vis('#histCalCard'));const m1=await p.locator('#histCalCard .hc-head b').innerText();await p.locator('#hcPrev').click();const m2=await p.locator('#histCalCard .hc-head b').innerText();assert.notEqual(m1,m2);await p.locator('#hcNext').click();await p.locator('#histCalTabs button').filter({hasText:'วิเคราะห์'}).click();assert(await vis('#histAnalysisWrap'));await clean('#hist');

// Current Position visual buttons + chooser/forms/save.
await tab('position');assert(await vis('#pvCard'));let n=await p.evaluate(()=>S.assets.length);await p.locator('#pvCard .pv-actions button').filter({hasText:/เพิ่มเงิน \/ ทรัพย์สิน/}).click();assert(await vis('#peModal'));await p.locator('#peModal .pe-choice').first().click();await p.locator('#peName').fill('บัญชี QA');await p.locator('#peValue').fill('50000');await p.locator('#peValue').dispatchEvent('input');await p.locator('#peModal button').filter({hasText:/บันทึก/}).click();assert.equal(await p.evaluate(()=>S.assets.length),n+1);n=await p.evaluate(()=>S.debts.length);await p.locator('#pvCard .pv-actions button').filter({hasText:/เพิ่มหนี้/}).click();await p.locator('#peModal .pe-choice').first().click();await p.locator('#peName').fill('หนี้ QA');await p.locator('#peBalance').fill('100000');await p.locator('#pePayment').fill('5000');await p.locator('#peModal button').filter({hasText:/บันทึก/}).click();assert.equal(await p.evaluate(()=>S.debts.length),n+1);await clean('#position');

// Future goal source, What-if, popup, dashboard sync.
await tab('future');assert(await p.locator('#mpfGoalsEditor').count());let t=await p.locator('#mpfGoalsEditor').innerText();assert(t.includes('รถใหม่')&&t.includes('บ้าน'));const legacy=p.locator('#fSave').locator('xpath=ancestor::*[contains(@class,"card")][1]');if(await legacy.count())assert(!(await legacy.isVisible()));const gs=p.locator('#wfGoal');assert(await gs.count());await gs.selectOption('g2');assert((await p.locator('#wfPrice').inputValue()).includes(','));await p.locator('#wfPrice').fill('1500000');await p.locator('#wfPrice').dispatchEvent('input');await p.locator('#wfCash').fill('300000');await p.locator('#wfCash').dispatchEvent('input');await clean('#whatIfCard');await p.locator('#mpfGoalsEditor button').filter({hasText:/เพิ่ม/}).first().click();assert(await vis('#mpfGoalModal'));await p.locator('#mpfGoalName').fill('เที่ยวญี่ปุ่น');await p.locator('#mpfGoalTarget').fill('120000');await p.locator('#mpfGoalTarget').dispatchEvent('input');assert.equal(await p.locator('#mpfGoalTarget').inputValue(),'120,000');await p.locator('#mpfGoalCurrent').fill('20000');await p.locator('#mpfGoalModal button').filter({hasText:/บันทึก/}).click();await tab('dash');assert((await p.locator('#dash').innerText()).includes('เที่ยวญี่ปุ่น'));

// Installability essentials and stale-file guard.
const man=await p.request.get(new URL('manifest.webmanifest',BASE));assert(man.ok());const sw=await p.request.get(new URL('service-worker.js',BASE));assert(sw.ok());assert(!(await sw.text()).includes('dashboard-goal-sync-v1.js'));assert(await p.evaluate(async()=>!!(await navigator.serviceWorker.getRegistration())));

// Visible controls labeled; no runtime JS errors.
for(const s of ['button:visible']){const bs=p.locator(s);for(let i=0;i<await bs.count();i++){const b=bs.nth(i);assert(((await b.innerText().catch(()=>''))||await b.getAttribute('aria-label')||await b.getAttribute('title')||'').trim(),`unlabeled button ${i}`)}}await clean();
await browser.close();if(errs.length){console.error(errs.join('\n'));process.exit(1)}console.log('QA PASS v3');
